// @generated by scripts/build_themes.py — do not edit by hand.
// Source: 50 themes in themes/
// Regenerate by running: python3 scripts/build_themes.py
//
// LZMA compression (XZ container) via Python's stdlib `lzma`.
// Decoded at runtime by the `lzma-rs` crate (xz_decompress).
//
// The default theme is embedded as a Rust raw string literal so the
// published crate does not need the source `themes/` directory at
// build time. All other themes are LZMA-compressed in the table
// below and decoded on first launch.

#![allow(dead_code, unused_imports)]

use base64::Engine as _;

/// Uncompressed hardcoded fallback theme. Embedded as a Rust raw
/// string literal so the binary always has a usable theme on the
/// very first launch, before the user's `themes/` directory has
/// been seeded from the compressed bundle. The original file is
/// `themes/Cyber Red.toml` — editing that file and
/// re-running this script will update the embedded copy.
pub const DEFAULT_BUNDLED: &str = r##"[general]
background = "#0A0000"
border = "#E41951"
horizontal_rule = "#3E0101"
unread_indicator = "#C1DEFF"

[text]
primary = "#E41951"
secondary = "#8F1134"
tertiary = "#7D3F50"
success = "#D7053F"
error = "#C1DEFF"

[buffer]
action = "#5BA4DB"
background = "#090808"
background_text_input = "#160E0E"
background_title_bar = "#1F040B"
border = "#000000"
border_selected = "#E41951"
code = "#EA9995"
highlight = "#122C38"
nickname = "#76ABEC"
selection = "#73000054"
timestamp = "#750D2A"
topic = "#E41951"
url = "#FFADAD"

  [buffer.server_messages]
  default = "#5BA4DB"

[buttons.primary]
background = "#000000"
background_hover = "#4B0A1C"
background_selected = "#230202"
background_selected_hover = "#1C0606"

[buttons.secondary]
background = "#310000"
background_hover = "#610B0B"
background_selected = "#701414"
background_selected_hover = "#882828"
"##;

/// One bundled theme: a name and a base64-encoded LZMA-compressed TOML body.
#[derive(Debug, Clone, Copy)]
pub struct BundledTheme {
    pub name: &'static str,
    pub payload_b64: &'static str,
}

/// All bundled themes (excluding the default). Sorted by name.
pub const BUNDLED: &[BundledTheme] = &[
    BundledTheme {
        name: "acton",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAZddAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdxLAYAqSusoSY4FoKh3sfoTHi1Mp2OEoU+s8vMF5FXiYk3Rj/WK4Z2AEo0VIeUMWponid+WUVf0smv9dr/AXBFaOzNBFVyQiZsBx+DhMjAXhwekRjvOczBzcfp3EfhpKMnb6xLX57HutKtQLD9vM9UDqzDe8IqGRTnOKILXvYI3cbHKJB0u6hbpcd1hfDBR8gcvKgyFHfdIh4sd5EAMks/14luq+c0qMhAakUx5RUei4/atdwkq6wxJS5OL5zNwdGz0yGxm8xq8oVrv5QMaCNTymmYbTFA8LN1+eDFEJdQZsXSkz2uj/2hxhB/qGIB6AVTW5QybQTATxWsQ1ES6vAIvxduFr+zbpZW2Pwr6ZQME6F3QVkbRPVr9M7V57Bp6/uKKZqPu00gXfhdqqmMGIvBz/Smsb2HCrs6zU5GPIN5qCXdJtbUISc/sqZM3bnIzqkHMdhvgdhK60D3WcjWq+1NEOMRjqYqnSYYkwss08Lu0ehBjBeYHkRPLhbKxIAADFR4zJ2xgW2gABswPYBgAAEiLG/7HEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "bam",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAZddAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdn98RuNjbtt2vekbe6iZJLSv/7XD2xYzl8nfi7e5KgKyYLLThy42pkgUpX5bjo+99niSx+YBAtGTflwKIL6MvKqaKucLHyNgmHLxXyi52+Yr/uKttXaBS3V8mRUGlFCuRXd2/tp4kyJDTULoMtLhKFjX48dazuHSCojRp0vS9aKWYHKz7puhkPVKuQVZJInqJdVFtJbeqlTTn5Gior9ScfIt3IKcQlulPlOpwA36lgh5246P3le/JDh3v0Iw62MF1st3hrswjNdmLdzsxhaNV6A8cflmVKgQmnQp0i0ilrxQFAFXonAs+YiZ6E//fZd/2X3cUx23bQVCyT8xGrF/zCRaFLPUrVsV3RmW90YX7j0W/cK5QqjlTOFMCUAlhZkOGKo4sa7RrPGZteeoztI5a9/0dnWcKW4sEFwopDsj8aMh/2woYC4g/CejsvgxsPWEwoD4aSa0SAmwjezBXpYMwAQ4pGD2JOWDJ9uMAOxr9ENInUxpNaCjBhnCxpmIAAA89nMryz04hQABswPYBgAAEiLG/7HEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "base16-atelier-forest-light",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4AOQAXVdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPfEOCzGO0W6bDEn9zZGlgQnw5ESqEW/VCKlIwP45VSoGS7bb81I1qvk5Xm3MlsQNreelNA7zmel7a0I4+ntPbRaT/cjXiZUMDkrAgojq+QC+Ih58bEtj/dH9sM3Wdy9LqvzYDBNrORFDuM07Wiun2gG7KWTLKJw3Q6/iHcDHakINH/YEE4kYntmgqLMf7otgByoa2La4iD4lBn6qUUuanz51trYr3MAFzO6iywGuSOS4cOTi/3lhMSB07dE8C80PCmxRPENTxuxpb6h/uvnuu9CDAXGY1snMs0aLGKXluigLFY2SLfKm65HHHRc/cQ7bFis8v31UlhMPt6tLlNFLkYKsQhIirOGVawL3BE4ucro3FdEGz1EX8V4qB+sR4bbptUziq8Q1tbkSSnwtgLAr0c6VZuB6BdtBMK8Bgu17YPcvhyvs0XBS06fYwiZRn0DEmU12SZpE4lfiZrQAAAAAAjXpjc41t4roAAZEDkQcAAK/7fFKxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "berlin",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAZhdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdqsQiycGqm7bj1Ka1GYtZOrRGkxhUe1mkHkjBvVNA6ogSYAccl2yHacrlhqwTC4glvJ5QNjLxi7dcvSa9Qu3xgFzIH1CT70S6rQmSAacI+GbRZhISXQwoR4OuV85pE0n5FDU/e+KlwO1lt2XQsTOkLG99YiT0ogQasLZE0tmKSBCoyLmGWJMbJg6pQkzBMZgelFLCgv1C5dormRl0xM5xJ5ubXyiFWqCqAWc/Mm05WityNaRwJDosPHBAfZBTl5PLEaPAdzm/lSPZTWBJxVxIvp8LfxbmjfAocHO5qeXDoYrJE7E+dJ6BXVpPcvVCqgn7mp1/QsWVU7CM4NTtR6j5TTOyFGMT6/nFoU1L5pYV7+X6BqkdtaJqpUG4oqRtix34xiOqEeunt9VuIigpBiMdBiLjNurkQw/ZYDptgjp/xvNytaAHtlSFb+mIRCiofU0E/JrMe82vuWaKkqj2RIIOUWRc0NURg3j2x+tgtFVwCLjhYlbbGVndvrU72JLdADhmUf3b242CwABtAPYBgAAqhLD4rHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "black but with important highlights",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAWldAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsVTO8ky4LDYJjdeMMgm8u2k3WYDa1eQAMemzQBKqi8HFVfh6I5i4EO93W9Tb2t9Xn4WrXLsqeNtai8YQ18HviZii6x1PZXWt87mnI3uln9RfaAb5W30BptIuY3ANJpiz1MFWvmYqIaUJAGw6NSIwJr61Irx47Guy6E2nGwcBzj5oUbzrkewOR+IDW8npaLrt9LC5g2o8iFxqtLQ7KFgaN/79I5/49+NHSSOnl61J1xtWDFr8gyUsZwqxeswJfTJSRn/k/oomzOYZLVu5WUMRJYk+olYxXlKI8djugliK0nBfRE7ipcfYEyQ3vzJOUYK9/vqgPZoAGfZCV8fwyGWbw6yJ2Iz4mD8fVMCG6CYKQOTb5IHfK1qQpk21hQdVn6lzAYVjalzBZIEhimmu0sA3Gv1z9f7t+wGobkBpLNkuU54XsR02ZiwsEmZ26FB2pUAAAAAZuSNu1Aafc4AAYUD2AYAAKLG5S2xxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Booberry",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANbAaBdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPd1ixCkfbZQ6nUBiqN0dA0BZtgoXDQXG6RcJ4fvH4pk6fSP6ipmpGbLTsEzOERr7+DzbBvPtc3N524JYXxPm2pWLIFDZIbngpoDy/4o9FBWFHUrZAc02Sag6e+VID15Rqog8huGtHo64LU9okeQbe9xC8eAEEGDhMDrTnkym7TY0X5olmLiil3wXGPGQzzKVbuEatb+Ut3C7Zuh0xx64+JmhNK4vEoj3SYxhHbR2/gnMph1brpJhCVniJsexDyKXrcxyXiU/U/jF09J0vkA/8JNyGWiSlPqpNr4DW5QcTbCyrr27kK8FPvu/S2xrvoiRuRVCCYtO7lw2b8dOCKikwLOfvVIorz/F69WrwBnnDepyryNci7LSxbqr4c0+DMrUvAFfVmcJbpDOdnV+qWquilsrWfRIhOaoQeOVveMBa41UQ3LUq/t6mQDS8Q8vKVQ7osJQJ7oH+Cxf2XmkX5J5Zs9uK/OZB2Uiyxq7vi3hTNwcTRmbmsx2ynVSKBiACvDqD97gF6uAAAGbTeqe+6+p/AAG8A9wGAACQB/KBscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "broc",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAaFdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdw3UfHoTaTnYYMk1jVxEBJADUNm0jea8ol6goLu4CRpN8vhAcYU6C49deYKO4UFND6k20MIqmOb3pF/t1A2iVuJ7DF9/5N8pbsED3rgFb5/zWzgjyzS8yqpD2Btk6LhfQ1YC9QBNCWgi/b0WhrMoUdHCkG1Gwaf2YxJlCAuM/DBMhG+/fTAbKRFM3DurQK5+ebmbvTMpg/Dsk0OpdZfv7quOWUdAxB2vLw5QAwi2+0O6vm9xQ/c3X1lKiatMkJ6H78VgChmR6/tCX3SBC7Cphfyvqckr4De4xq54xEWI7iS2sBa+Svp4jd++lTGAS5D5Vk7iqwj4cHGMkehsPtDk0pgluaPLkdEBLZqYDbPKJXivWeDlVhOJHWYFwJ8t3n6QEnDT4Y/lulCkTS5uyxWvg7I8oUWVTtFMu3vBR/1Hgs86X8P37ozjm9HgDRN0+NpUpH/MF6T8gDrKlovObj7cxBme109pAZs3MSwwNbnZv1NiJf2j+nwUAaY39dzH+BHwxtpWR0hPoAAAAADTGdLN5B3lPgABvQPYBgAAYkPMxbHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Catppuccin Latte",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAaJdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPe9P+oinDgezz5rQm5N8Yl7w7QwkeILweTMUCXIyG5j42qs3slh658gvFwmmOZjyqkkCYQmY8o/Nq75v1R6Vp3PBnaOKgrrj0LWiyVDvKaJMUc9fK7hVoLwWex4/UhlAWySh2tk1mOwFQdJNRAq4zUjIMr1Eu21y2MCd4Lpa+lnv8GkUsyGmybXZLN1B93lb/rXHChtpkrarshR/0vc2CECBT4xtRG6UpNArzLX3Nc/VIuZO9Ni/dB05Wl+56kyhkiyk4qNdoX6qghQHRfR5jqFXIBGAG/WNBKBYTg4wvCPkLBhmfiLI4NXOZCzoVwDMtvc9IIXPxhVpZbaY3cp4kTkItt19bA8hhNJlZJLw2DFT8fwFm4Pc2m+FOGsCO08aHTU+yCBw40LRDaxsnlTnwb+0/17wygp+rUGO8adFp0iHvxKr51ZytghF12zpDab+2BbJdlZpj50GFW25KEmqhzA3aEmjXQTBAFBYAuhoyyTskSoEsKqYiHWYBVREVBtwLhL41eINcOh4AAADR1k2df54z7gABvgPaBgAAR/lR6bHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Catppuccin Macchiato",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAaBdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdnyJtNs6hpmMF74xEw05atsmx3q3HGLgjzFDIR1R4HcN7QXl5a5k/VxqUHdMMRhoNaxkuXhBgfaC1HbE9xttfT0L9WYUMIsU9+WWgl735tXXv0VQ3vLU5OmDIKzR8zCalVvZ8vmlhLGyLyZwrxdmd/tWSn7rTLfLYlwHjKaFTAMqD8uFqneFwlBDE6+ej3xvEME8pdnl12qSpuI8CeCxTlixVY7rDlXPoK38aBG0OXQNwrVU77OWFfcQNbaUNMMF6Gc3ldmeu8l5teLmuFNmn16TQnbLNbYkc6mcQPsiMrtZUEAS9p26c0XreLopgIyvtc13w0+cI8rYecZaUqN0vd+9xoDvXnK764qoatvgZ8YWoB87dNR+nL2YMy+uayO3Iy09/Qz4fiVcoPg31j33+nB5+XTd285F0kvf7YzwE6pNMcNkyLOeBr+xB09+Smzx64GtDY5IqhDw1v6AROujGUqBvl8QH3p5sM0XYxuGqtelcsePsn2WN/wnL7QEtxho9JxZv0UAADJAGv09MuJ1AAG8A9oGAABMWJmkscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Catppuccin Mocha",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAZxdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdq8BTkQTutb1fn4x68E/eVfzCj5OByzUP26LF2T4kVJf/Cb40KKPVezhHih18lzc64Kg9E8YbrvbjWkMVElvqZ5c62cf5wcOFoi21W0znihLtd3sukCmQKVf81exOcnLBTdL8O7asduJiIGvk8d2W+OoQNbGcT08EmaMi3XYZQtDAfT0iVDGA4vJW5O/JbX3+ybDcAaVjCWeE/vbEz1ce0S4+WUvPgOh5G+1Oe9LnEQRaf5nekzSizgRn5S44Qn+6TCet1lRuNoeW4f2yHSiSrwlexvkODdDrddTaqsRnW/V8eSP+ylU1fnbetexf2f7aR5F6XWapp7akzqmIvCSypYsy43qkyzcQ5e//hKKR77DluKzwzRafwsWf6kKmUAJzCYNCGguyCWGPrkPzzkA9D63KyS6cLOGuwZMrAaWaKa3QFApsXRI+bM2i5RVRo5BLluNzKOE9+9wP5jpcwTPeC5cWyuVgGPunvNtoPjLeElLXcIOuYCS7FzD+4oRn8WpOhwAfLqx3arSu/0AAbgD2gYAAFoaCD+xxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "cork",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAaRdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdnvSOYU+k1BlzwXM7lBew122Fp4tdowsjdu5lL+k/oGavmjJ6XkNL/n4bOMTj1RIQ8LiezcYwu7kRkZngdnKzw1w1MpjQ/uxdOn5bussCA/qBF2LY2ssY6yH9laCS3VWP8+8b/fuJcjJMoxHtTDVFjGQrRJQq2TlU20Ecq3yAWxVs3c7bYu+MJUmR25QyK7EOgsHoASugKQEEgzzAoMnq6fL2b9YRFTQrbQtHqNQ3VZz4EvcMXTi2HL9Zda+XiORUoGQJJVFsb5XMCBZDlM+MEc9EP7D+Xtecr7YFPEIAOZg5/vSVVhUd1K4ttG+diz0/k1Vk4A0dkoyBx0hqzRVPlhgkINGOwkvbRE8T20yDl6FDLgwwj0PaBTJ7qoiAzpmGqlvrjIIBNs1lA9ym5p3V8gwi+m8Ag1kXTnR0T9ZpiH0g6XWX1hjShl36Gw1Gxwd7UaCeV1a95cufr7mIpIG3dUu0DVHqs3V6sG8k791GNPud3fC6BGuRDfh4OgYBVV4cVFKZGPG1t1PAABgnmccm3/jBwABwAPYBgAAfV1wcrHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Cyberpunk",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAYFdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdjUG0w1Cc4cC6E/nWYV0NrFa5BNpvq+EH1C3ITWJNA8Qaa1t1ZdgJP1v7qLMXvjQiXY4qZF8P8wL7OP/AFNIUChGzdtWUpgzt5TNF3vp8Ds9yfv9P5FKuMnsPxBZSVmMn6AcEPKJ9koQCDWbVx+/3c0fZvyOXPZ5N69G/7ouZfMJRQKMr5MCTe2WvZ5ubLevEHMStn5FNRPsdMFnKXaOme0qiOKuS9f1A1DfsGwIocESPa5Fibt7Nni1Ca8Bi/1GCD/nNmDrAdfNB1Z4OKEEWs/HFdg1zKx+maL7S86BFpRhR5XtjMdKdrqDNlb/D/M9lw4DcHWpQFbIW6krcbbclFvG1FE4qLAytTtfd3gPgBSrYNq/wfNUYGr1nK5oq4hH0popv913VohfPqeUyQ8eTAiWRUIYbKQVPLBfmy4b8KIW4yzlv8DjRjCb7/+F2WvrMfpedFNJxnTNL1ks/GutG/83OigbjrYAAAAA+XQPUIbgB/4AAZ0D2gYAAN+OaWixxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Dark Green",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANuAW9dAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdjF0cd4duUdCKxtnRmPLyy3GqMdmt6Nb2ybkkAMP+94y67N6I9tbGoPwLcy3OHVyIU08Ngpc6PpweuR0RE1lkbpBJKI0mGJVakLo0ZI6OJ1Qv7jpsJQ4uKotDU6871MVlw3gKF2NBDbQg4pAwZ8ior7yQyZ9/iK3WlwjOyx3ri7u+JLihnPk9T6IkyL1XJ4u5ufxDt9hOlAh7LaIcpWjpox+prdAx/XANqtj+chCsKLxA8xFXtD0OKotVJlZROA4Y5p/DwJNMTnozxhXIwgFRjgmOLbyuiUaxvhESLkAuXK1GLV5t8b0o42/U2RAFzOuIahioBC0NFK43QW0dtbIJvtK0Jp3FaQUa9R9Hc/9pDwOf0mRZJkLb1aipYjyB/VyjbNfR8Gb6lO2dAQ1CyFpYZ27gS/6U8QNwT0D54orYp1mrxv2cmqxKgvJEiff0K2hZqmEHloAAK78JHG2bR5iAAGLA+8GAADKZxN6scRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Discord",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4AQ1AcJdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdw3UuGTBdCXdlOUOtQfv9g7Up/AffC7wWLmGv+Kxuii2ENdYf2rYcdnD+HpMf51Yhnx3ibOtVsY7uhSyZgPW7c5AGiG5MjvUaOTRwv1wJVn6/fAdXySucsXPleaOlsFYb9UCyEk7sWeVL1lVHX4lhE0DLNaih8USa10Gh7z7AYYaMSRMS+NMyV113a9jLi+RZzqCg+LrDrNMnyme8BQ2558+g1szMBsFATgxqdgrbD/ku0XXY3Wuv1BwyG8lWEGTh0DsNkZzd/gvOr+VLvQUdFpr4f9slsUTNyGLaXOhhzwZF0ASfjf4N85QWvn1WO9/Ul/qLGz9Nhq1NVggpJz6T921gDo7KLzHCMsYvKhOTL7MK5FDF+xvQ5oImNfFwsSMMby8nj9Nwyndu5t5qrCxKMJBlscP+64Zl5o6QGmpSC8Nhv1zMc5Os5orRlHgxhdwxp2EazGlGhyNSn9ZAJN7HndrIrjey82s1GfE6yl+ejW/0v4xan9aRZkkS1m2KP8yY4eo+G1dGbqSMSKy5AptcAJqZrb2s3W4PjDtKYDEIEO39ycufC4dAAAAAOKKcOxLZ4DOAAHeA7YIAACsk8uascRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Discord (80_ Saturation)",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4AQ1Ab9dAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdw3UuGTBdCXdlOUOtQfv9g7Up/AffC7wWLmGv+Kxuii2ENdYf2rYcdnD+HpMf51Yhnx3ibOtVsY7vOkil6gEVezIThRth2EVHCHGlhULpJlNgX8Zm+otPFQMHmE6fIUlVyJ8TgthZdPFmIYyzRuAE8Aj03ViPmSsqdqqjhDAmVxnD/eYM4+LMZB72zhrNB4AQU9xCLd7DPOyKgaHIbdSsS3/hPHqUZOx+P7WJwB6dVZQMpgS1Ko5xBjKnZTpxwIp/aYzqLNm2+QobO6PWNZJ0n9D0/YFrHag2z7FUs+2AiNpXUJqQgtCF9JPCvYYtwL+o/pCrlizap3cAaRvZokFDF349ldp29fsJXM5yNFzc5sSxm64pJyoy8WuEWkYWkEtBmmGmJVtl9eggb1mBGoUpPwbytXPY8RV4ZggE8PxEuk8/Gu6bhsB6i0aTsYMbqH+mXX4zkWUD3qW2D7tezA564dIQWJdeyn+oIm6MzDNBUdParbEKN7uK5xAFM1D6GQqWYT4u42cNVsOInsraePUKJca9Kxejl9PoVcjqKVajRnLiNQuAAAADOe6Ijyt75MAAdsDtggAAB8CBsqxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Dracula",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAZZdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsYr7SDMRF/I2zolF8t6F5jQykiN8906N3AFsUFqZD5HIf7gI5Y89fV+KK9oculX8t3tdMsmdgwRk8iqlKtMJTSoQUHc492XBKiLuScYGKMQ9ighISWfAmxPWScGmp+T03hIxTAvecKFLjYDzaum8ik7xpJalz3osvTq1EMXQCSXOvWRYYMq/VUY5+N2rhKdbsKVIBkBAP+2F8UJKl3b+ZJjqijO0EU+88xOSTX14V/UQm/lQfoKwDZ0FVXpGBNApn9rxrfX2tZBsC4HI9418Ep313OYquzbqr/FC4V5dnAXc2TsygW2od0oV8hh2BH6HtcSH7c97s9JX6ULsQ2/UDOWFE5J1MDbcnlG0DAtFO9j+9SylaipxRYpG9ao+27gKcEXhxUh5Xgretmo/rmNgVI+oBJo3hDTmxBrjucqeT8BWWwH/ly11JledkU1meaBCc7445zjgFGq2bjcKhPgnMUu0L/J+P50RRrG2oPottSq9kB0Th7g7jPrygAAAADdjrzUj1vI0AABsgPaBgAAPDmTnrHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "ferra",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAZldAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsh1RRuvMB+vuyvFmxvjj8eD9EytsdLpjHW1rFx9r4kJmwpDrx9zKFmoinSbiX4yM40p+9cIX9h2TWHLnSqywkb8m8CNiz2ac17n3UoWg4vHsTEFUHmJ4Yh+HpsKyFOkvzQhSRxamxBq/djXWfM1yZnEdyBSWAxlvq6m7SIWU8HwqjYIuU2LL0cWYYULghtY63sCNszDQ3xxpfxzfbpPp06ptcaFS0MnaP/HHTNP3xVZP+p3tDqiIfXkjFmK7par3qvP7q93m7tX1fXPi1uNTLRkZBwwMiXxa85CL4d95F+NXX1z7750kn2s5bCtWsCHIkgrW4BWV5VT5CaW9yT8QnBkilFJROX/wxQGAjpDpMYCaN4l+f+vPPWYfgH9u+4krLeEquFMZ0AndFB7INxWRoWkihlo4TZ6lTILkvBLzDmyUkoFu/g7Wjc8/1IGkqDGA6ix2OAJwJdHTtyLhQIaJul8DuNg+nJmNtiXvRMG5PWh144F9Ut/4Tpfidgm2vgAAAAAJSGJ5/tNsp8AAbUD2gYAAIQJloOxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Ferra Light",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAaRdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPfEPp9TkLktsPdom+oPIyBRJxYwQjruJbPVl6YPRQHH8lKNzFt9ttbcLtI15zR2zL6FTOc4oxUk0oVm01MCQFFh02DGp89Ntissp7nuIId8KCwOP14EuwHE1+2DISjROz45ENo1FowcHzZGD7fTN/udMP9FUbTnymB+VJyTJ57DjjvKkyeuUvw0z60vgNX/dclzD5Pa71nJmtUsUD41ctcAvWHXoGdFv3AIxOCziznaZu+dqEGklkU/NlAPWBVhJjHNnltHu4N4YlY+nmHPZqT9RZ2jNnJ0RWU//UTEvIH1dgL1JPI2bM2Lpi90jm+y5k7l00OMk6maD+rezUCsYX+UGwh3E5W2XLbi6OqDQ4i3WnT8kj3Ab258yq95ozFWViMrR4RnkIxb4T5zqemiBQPry6l+7WFd73LWPiR/ceH89oUYDHNOjhKt8LzqeJNK6kgDqgEgQeiix+IRAYABj8glMfGqjRLTthOCAUZZ+cJK2XA/HhnoUzYQzOZGRRHB07+6S+bjjxqRyWAAD4aqfSvIcYzQABwAPaBgAA9pV52LHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Flexor Dark",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXldAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdn79bFhUz+gGJ8WOeD87ctsUUwUxt8s4ovMPH0y9yJmkTzSYPO7YAnBlRN9PzYTZMii2aVuQO5jINqNQFtjizJDsFFIVappXKz+zi2dCAT5zRf31MuHmfuHPO7IWE7DAAjkJwEsnVOXxxfANM+U/CJPB0YZ4HVcqAYEXtaPFaICx1oEB7IbYfj0ZsJNzzavAWdRMzmLChwbAYNHW9ElPGKOrD8PiFmr0qRlzEwhzXh9qMTxD5oBi7pEnpvEFUJZ7r8L6LW3bOvB89yM1PP6EJK3+9B2ClbfNIwCb25i6cEC3IYZeKa/F7lEdhi4Z5BKRqTlLbaAUaoeg3HRh/VSn793Z7olDoqiWOlEtohpG61W7wN++crTQeebaTL/+/1VcThCGCOlMetBSZFEdhArCeIXBBMcA4jWZNag0jRJQhT3seLUkfuQ6GckNAzqh0aSXWhZnB7J19y7CsTSC6xX2AAAAAOqr+MsmuA6MAAGVA9oGAACyDDqEscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "forest",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAYxdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdn98Rw5h5crSXtA6v+TALxdKii8zn6LNgDoVax4xRsu2tgbDzPyk3gfLcVz7hlbbh0iIFwysXSKuOKy10vykAvj5STsqB+P2s5tPE90ZJjH/Gp7THo3rufOHO88nEBPHdLO0rFFc6DB6KXnGkGj2MhMPdLkj+Hvotwy7dC4OzUi0AJLhomcoqHP6PID34lNfx7IH6kYAPpFaw6rAF5FmBrtFujEWXEHoETfWYDJU1pnJa3iyW3qwqj1wJgZmAURl2O+g5WH1fCVb8+FkgjDMb9NltCnwoWJDTJ4UeB/Cu4zNFRSCrgn4vRlJkcn4DiMOjLrgAUdwPRNvwvv/BwqQ1BwQcsAmkxC7jvBtWAbZxC3Gxd8Dz1oKr2m/+7BRwXTu6jajpmk++HoJRHZdl/NRKQWx0lTyEtspOb1He9WcufeWVV4+WOSgaPdauNtQrP2jcDZ37K/gG5RLznmVX8GGp+dNFApq87sse0f+6ifQylroWABA3yhQ6a8aFQABqAPYBgAAStDXlrHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Gruvbox",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANbAZRdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsZIK6Rzf6Zo69xBdWsMIYvEMdJErmG57kPHlq9f48L9wqijT9N1ReL6ShN7nK7csyz5FYZ7AUX9IGT+2aJWgjmq0wY5XD+GRog7puQGgg5FRDfDw1JXku5wHOykT+x21r4Zi5YQkcYq8r6JzvitL7i47gYYz9z7EmyYZSEy81+gRbR484wNtYoPES/uA/1z5JZiCN2NWf11bAy2CJn686pDeZCBjxwK/nBodwQFUi1ZsLOMLRU0+PSa6MjAFSaP/yWS123ud8KMhA+/oQFK2JsU0V9R+06ERCY1t3jbM4zHgtp7ZXvL/yLGLX34Vr3B3b4p89fDLg8q0rLgzvRbnvgn0uqzxY0yDlNGm2LFPORiyqiEmS3T0//NRyvZKAo1mWjTPB75s7LKYTSuaaVU2sJZFsqCnuYFvJ3bf/v5ZbA5GCkzXxmhpBjXYw4ZgWfzPyZAnWgpxYLT4P6pmM6eMiAu5r47gd8H92VBV8lUYovtI+qr53UFqDAAAEadSPDL3wx9AAGwA9wGAADrxzD2scRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Halcyon Dark",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAXddAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdnqQhpZUKPBMzHpscgDPwA3JmKA53f6TCy9idNBKE8PuxMyYOqmr6aEp+JtFK2+uws1Ak6SDROc4iXN7sG9NyiPj2Jue8X68/0ApjpoJw6Ubcbcq3sjQ4n5ueUHWy+t4MRvI+H+4RsuN21pO71oKXOkNCCN59i71Kxnmx0c8D0Bza3iA3jsDKwBiXvO3zYJiJxkWTyhFvj01bJCVh01z7gle7qUmuyjUDez/yeC+tlKH0CVSkrT+8HKJBRxr/oWQg8WGlevUx36JYy6ZnnCMmKTXf271wi5TSD3LYLB9Pa8TL7pxflANx4us8OnoU4KWfT6YJIlAOLRS1krMs8vxzInsyjLqww8cNZi4gxk+UK/7Htng3bi5zKUMV8oXNPNLxkcLuJQAO4Ff4N4yBE0l7glqCnVqjA8UuQGG63wj/FcdgnzFgFzR3A3UnSJvqSSdoVT7TjEAntwIBLgzAAAAZWz9AwN/dSsAAZMD2AYAACQnavixxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "IntelliJ Light",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAWBdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPfG1SFWk8GTHlMKCMG+zCwBpWF/exZVyED8+tFGaexTzGfOP9MlwTiLJVnrQV+qGLa0gLAQy5ACLnEnUeZMs7k6UUzclBUm9LD77bihCIey+DipMGvZ0lC6W7cQDfKgxc1GAbJbkcCghBL0accrYcs8Aoiad/1GOxOSEgQwuYmwGOVrvJJav2Axr5G9XlwswR/vZFc6+8hxqGoB5g+TPt5FwCO/p5ISuE5YnXP4kWN1hrAdYpsD9mrASIYx9giQHl6bGnkhbAMhWWrIxHYwmSV7yNCyvpBHhwOarTjsDM0rR0ow3DSi1YZXgOFkaCWvaMbWjxMmyb3oDNn4vMg9K2dLtr1dLwtrxGYz9auXAWeyNCI2xYKY3bX6SAqDTjbniZPwqg0DBbBsCPPEjJ1JhmlBDcma0icQkKj74D7hGjkOnjuREpJAAAehwACkhVIzwAAfwC2gYAAJB7oZaxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Kanagawa",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAX9dAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdn+P3KgS+LVomDnoEDHflwjsAPZZbWHjIr+2BMFJg0vVKoPpBAmJTRmmzFZLrxqG0fNYx9wccmykO/KzzFgSDkrpW5PWdNEqIwEnnmFoQORgesb/T/vMZf/OimWVSN/L7pn0z9N95/a2XTfqTIyepdhUrAW89GOAyLH3aXFb/RDurAdl4ZEPQ6U8cmnLzEhXWiv73TNYOfkkzMD+a8jtzgfWWvloIxP1QuqjqzaxEPRbqSeybj6MaEOGD7fNKh/5Z2CV3Uze9EtSNTDdGWV34oj22Fd2vh4lVGAO+V7u+afremlogykZLJP4Y1viSjm8E95GoGHNgJ7/Qp7O0ALTlHCefiAC2XeVRLJM4f7JHqtYM+T1AUaSLHhnT8H611dQj4x4rOcjy1scntPQr5JaN6CS7sIDoXCzwKpQ8reRTrzu44QSCFayTLz3T/H4eQDptOcxNyD/ULUN44IySIMKPayurg0AAAAhjfcXZA7IOQABmwPaBgAAwm0wvrHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "lisbon",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAZ9dAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdns/0tT3yn25ah3CHGnIW1QHBWSwl9Mf+5sZrFSicQSxNxtCJS4C0MwLO/0E/1CWZn5kZtbVUe0eKJyxQEhkKqa1lvPzoaMSFsbuDBpV1Chy7hbfoUbrEFocnO2vtex51SOrIewY47BtvDBmcCQ7/AIDzPiW7QU33qp6taafE7tFhvUbO3i743rGS/vpwEaN4qT3Py1aLS0+uSRK6sGspOoNULFHML5c+itsfiPR8MH4jYBsph7J+9NCDZG/v8lpGJkLBqwhqAk6YrJRofvXAlme93jOo9HMHKMhoUqRaKUa26UYScFMTk/n2ifokoirBo1BskymHiibD5BzWcbJTkWObZUOnTtLWj8/NnzUOJ0fqbHqjkHAts+kt1cMFvhto1XHLFqKofVjj6aIR+0Z90EhTJigM1Ly60ThfgBfuPCmIj7TDn3ZK9M5LPrDUMwbZcDTK9fGWzurfclsXmLQ6Rwch1e7L1AMbMHrbQlVrUhGVk4flhbqNkoeHwiys75yTqU0vAAAAOGDAbHEO0vuAAG7A9gGAAB/oJUTscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Macaw Dark",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAV1dAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPd0J+gKBByQpLOIST38MimBsvtviGHA5pdz3XeX1TK6tha0HlJs0xgV3I3av9O/A+ZhvvPON59Gz7qlcln55vJzUAz5fmD+m13EbS4CABIqofR42sD9LqBxblMxGh2GsIyzCkk5CfrCw7hlxGa8pHJaATdA8HhFSzoevZBdIAwNluqIGSa0bfiNYXmXRx+LqVJyuXSrNIRB0ILiIr+1oqP87C4fyXTFy9MPvvodO2KXsB+wFpa5NYc9kFQONrqX0bPWYD0X0wkKVvQWeAGhU4oIOBgynoqxHH477K6L2eRwpRt+FeXkaVjubZSeZNldUD1P0djt6mKQiqNw90Woa9pvXSj4/YWHh/a+XWsDZ6yHzyukKN1kbnMTIkIA24eEtoxRwK1d9r7fkKnGFdKxS19rMhRGeTkpMHRmQNXTqqBbPKmwAAAAAATIMgTz2LQcoAAfkC2gYAACPqbMaxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Macaw Light",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXldAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPfEOQr8bVl+XgT/La0scg7Gme8F4TYTBuszo7rEjxlg5H51TJvzpK/klYj5PelTRtV7RdUQb8+Kfz+kPDIFwRPJOXP4KI2ERY7azYALl24JvhxJPxVnVlBhZ0wh0vN3NpoC/EyiogbHBaii8OgCza6uh2YuoawhIa5K+8T5QeP566g1Jxwu2f6c6Vx10e8LuhvTyUqZD5hynjm7zlqaIsRbM2j9r1YbTD7ti3iIlprzosxTszUZLPIjPEPg4ScYy4KQJZbyij9Kk4ahEofh/sm9GcaVp6sAGHCfW8GB4fDzOW7diYDWjSc1YNp6fmA8pUp1PcRO5BUazW6fC4ykzCcDCof7bviG1HuEhzC4dL219HAo++0fcwboa1Zf3KxcK17HXnHhiOjH+Xn1EYFc4iPO54b5SUruhprvSzazzbUIXMnIrKsSOL3y4+oQ+i5uY+jNKhtcd+zMosAhomwOUAAAAAAPk81CUGE2suAAGVA9oGAACyDDqEscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Matrix",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXATVdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdmWYgKBByQpLOO+qwPf+KA1wemGVQZE/gTNqfHZ8aawlXxYPLeePlIKOVO/WIeaVCC7xsqS8NTfSUV/Bo1ujLSRRqbDgJUwT+jpNwezs+tvy3bqImHZWmmIALYyGtE9jnJsmLJCXmtSWdscPuwJTaw2G1+ixodb+TCO0GlFeui0u3zPF9SZLNaedF9NtZgbsf52lJA8WO+jVgvc01Ux0b4C06b6fXfKuM+CTNK84eQRTCFyLsIfe2hmyrShSr39d5/VljRsYvu/fPoHCN1v79vEqbWTZmkHGezc5bUJF24VCefArV/YztVTTUH7E4rJAWKUT2tFfyKGeBrTQlgzPvnLe3b7WYNX4Fdeko3z80s/r0aNQ7pH92oxr5AAAAABaTpeRu6LDPAAB0QLYBgAA86Wah7HEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "midnight",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAZZdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdjWFrHRnKi1612swLTSYBn63O+ermoRogewKxGYjGbZivxjcFeik0miQBhcZ9BDHEG0k3tLwrksxXrampN6eVdP1Kc6sPMTu8x/34+u1bdplfGF+PEJoclqOzixd58tnD6thwadBX27424PgahNhoeT1jwTYLJsBOyuoirPkHkStPyucgaqg+C9Gjym5eeodj/7vIF3+kAH99TBTnivPkqRWiVffi7THhxhegmprwnol7ZNpDKWnrTCcJhYgJbUFiN+O+t6wYexro97MS56Rjx/AgA6/bkGmWtkud6olU4SHbrKOj7t7JTTvZARXlg9SFsQ1/NvdtHu+kMBRDLjcM5R34Nz5hCzcFaHjP9Jq56DmeH0cYDqElCUs7XUROqsi1VjcyamfEXJhc5kDhVjJLkaK1Uoh3UYSCMSCmyMAP1ITtCbx2mqPi7RwRXnWChcpOw7R1wbP8cLG4ObZanrRwP6YGSyNpvy7Iu+PhTRj1W+dsT9An/Vr6FUN46IAAAAr2/+hmUaQvwABsgPYBgAAt/GaNLHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Noctis Lilac",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANnAZVdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPfA0X8buNGfYflBzR/1b9SzjGSsO/A2LQAWgAWKc/YxkmCrTovkh6gmqiu/QXnpvN5vtFhFtvwU3uPWk5ZAIDbQjXJsO6Y49WGE7jmJe98DUHxiC9+H6hd3Tb/iyuDwA9YjWAuql2hZ5YvEppvD7kJRqun7Ozi/LTvfHUNir/TWUlrvYckbE7Bmnx6C/rZ/WBc0tABKgAcBPCKexrBvAqViJfhzHEsYLZ+bWHW6oCagpQXEj7hXq7Jw6Ne1enZwwVhhAS1RPi+I4dYAb3D3qVVMAVrW1TPBcMw4g1uXjEf4e5Xi2fQvTNqfTxs1d4UnZjaSeOlMyosKZstUziOiOWbHoJf+hWEKyAnrtbNUZy7oUkJ24wvmq2c3ciLEtLG/pw0g42rlITfTyF8YHxPeTldeCnRsq4CBxPEeLxmAQxF6c3iWZPWHw4Wj3QyZ9NexnNUXf6tdAXEfjpuxSk4qcoP4GB8jKfI2zFQphASWT4dC23D2Xgx8CydD+0AAAAAABKbORLqvmCLwABsQPoBgAAuHslQrHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Nord",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAYBdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsj0H117dd3yABn4ythYrLC8S9LI8/8BWhHVrHxOmNhMoxluNaw/WGMDQcyQy2+TehAsBmU8eyRhJdsePDi3wuB/eN7nliGD2LdZj11NFohdh5H2k+neii0/0rYojSXJhM3MNS314QKyi1qtjoX/56TeQp7pbUGDl6VStwSlAqXHPUnRaiaEuT/LxCSB/98F2pe3xdf8MBgj9IjIcyyIJF1Mzy6vP6jODEyrYRRqZkOTBJMCkicyejvCVE6J9pk+4+H0j6rML/l8mkYAFcWH0ibIe7WbU9qTbWkTj9H0YeApTKPhOT+Ktgh0CvDwSRdpRKu6uDgqw3y6hnOhIwqdfFk5qkIhdlT+FJGRZ5UwjnMOw9J5jbw+EIXt/9+7+DY8MLU0UVCV3PtKwV2gWM5ar92kDsSRVupzILZYqUg9XnX5DMqTkwrwEEZd5JDio/kFNpqWpHm0KPFMKBnJvuwuQF5ThuFBjwBC3UA/rlCkmAABnAPYBgAA8ZU8CbHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Nostromo Terminal",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAWBdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdmWYgKBByQpLOIST69ozz+AjjhcKTgIo/3hTz3n9vETT9yiEXiXJSKnbJDfxPTZuKcYmD+TsPBLr2yT7SHW2HK9FZz2I7jwuSKmLwkI8pc1vCWn7Amf4gJhgib5ECc3RjMzTV+HEnqvm0egaC4qhr5EMPg2ZSky/k03x1UDP1ZRLYg9129j8jmv9saxDcwQ1AzmeqY6lSMlfSi9Roxr5X0rEGtvJdQw+VePZQvTd8FJoOd1iaVO9JMRbuUfHtAfIPV+C0mpDSJdfmqsTQMutYHTIesc2t0NiGqib4ri6yub/g/7IJPLGijNfbo3AtUuNfgOgffWxQ7qAQT8WCemlNxilTOKArmABQoJrLe6oHSNPuusYV59Quq4ByrNbpQTFHgMBWa3bPXTr/E7rrEv3ASoL1HPXAO4usMYYvws5rp3XPMIGEOoACsuhcjhYZ28AAfwC2AYAABuzqDyxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "One Dark",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXhdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsQyeZ9cxbAXRMHUdCVYNnmRx1VmiEAiX1CM9FT7frQi3QRI13UzEKeR5/Bh2JxUMSftfbvok2gqx1tXpqdqDCL4+5gWZwwEM/6zRzlk5yqI79T2nENfX43WXhbgXwCnDYcDTbgSZ1kI148/BkEHP8T27AqaKuRL0ribLEKytxm+nhR8w1vv++Br/YI7GFBwAZ4XqJoYALH4WYNfwzDQuZCbz/zsmpyMeTXLMwdepU+PPcLVWp6IUxzvGxN2MZr38YPITmfL7pFcKTnoV54y7FRHGEuZ1bT4CCGmarTgf708zdgbv0nxBAlLbjZ5bWytrJ5hVS1eghjZaA2pYkl4ET5dNdFw5jE7itr3qVWcXaS4ojaUYP7rTHhA4X1xhp+0Rz8IgUXY/ZGaYpHUne8tb9ADgvPnYrOjQqoEpn+nZN1lpUSJA6eZe9qbnkHHKb4+p5BIMnw4l8Cpm/vvCQAAFBPPaRgDBbwAAZQD2gYAABffZk+xxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "oslo",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAZFdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdjWv7YVTATD3u7KwPZ9a4cvuelI3hnItg0aPIDv8hAlgAWrtk3gDQsUzcTfOBX4I/iIIbUwwZQ2I8U2Il0iq1F++jxEuHDoD9pJBaRiJgrygBMHT8iY0C9phj4reiiGM0KgKshQW1U4xHLEyjlhhAxSda1cUr32tALmAL4uTrip8u97cbLFEaXOfgqRzsg9bde8ms3G3S2Hd6vA5Ir2dmU69NH35PUxxZNDVKfg075w5RKU/zo+kQpovYOO/jNA/DCgOBTaMrZqW4elUnt6zL8RITSb4nU/Hy09PPkzfnvpI/npIs0TcgOaoKuDECRxMZ0+OziY54yI+1UXm4PPsNb5Imtg+Ic73vyyLuQKitlWHSNAEvcAAOBSiLe3irtFUCUUWhLcM9L0TVBd18Q6//bdBtVuqVNJjJLg7Sneue0ekdagX0O1/j/6V39oYT+lloPUxepv1u+mw/e6M5wNQ84YXXvYJl+3k40/feeGQiqI64JDdtlcAAAAAAPdh8lxAxaoLAAGtA9gGAAD5QRrGscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Oxocarbon",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXpdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdnwrvWEy4LDYJjdeMMZovadq8O3S+56k42I529zcG7QAsH2NW1xFits+Nq9DbiJqmC4b68vidM4hqQwjpudaEbILcpl2or0AzPq9Bq7n+I+hct1mzdM+ARd2Rb+GkJWdp+cts59gPwvYn6pWC2DzKIp/h6F2j0JmUOrrY8a5UF+8gAgsXWeGSdUnFs9uZHGqDCrd1vDgxxv33Ti4+BOvZ+ux110lxOeO5sJ6h/n6leFQ9etSMrpn/z19cpF7rLaKfNo59BUXCRJv6ROfMlxXL2HyV1yuzj1xMBccc/cAqyKDcbOgT2qiPExm6MW7x3uByqPKgoX9xa+8/aj6U5kzwoiy3W8PBSEmCPIElAvVcYFJc2BVrd8wXvISZKW5BQsR35fU/ekwfEdgebZVEcTfZtJFUl1AU0oFehjcjbgezv8KEsGDY55Ma6+V+S1uqmecPcbcT/RCeAMvF4Od5TIeAAAAAGBW3B9hTkaqAAGWA9oGAAAcfq4CscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "plum",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANyAbFdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdnsW2z7+4WAQws8UHbzz5fzna8KI6eRlZ0783L+wqI+9maH/p31EAL+U7ftzSxBOnjhyhdLBWJDI9pT7EEXeW9H1JWj9sXof9lvEAYFR34/gzqLfcV7y7R3/1pLEZKZs+ZukqdvLZ4YKBQBW8kKyFbF3ouOOIOEqsUQS3cKlQ0NBcWEYZY/f7YG8seEMEBOL1yvVfGBkilOWoWdX/un70Y7uRF/5A/yw6e2l9zmtmBN2efeMgEwQwuPf0ZdWN/pTr46orxkjFZ+S0aYPZ/QuQdUFVYu76z68hXIOsz+1ssguGlDUjcCwyF736vbk1eR7Y6SBVnZdW6feINtM6MbC3s5IKZCe8v1wYvMLghvr2TJCTdZJJZftT0ANkOOVScWDMwVw5vH4H5LxMhPEF0/vHanw9yKPrZEm3OBwuJwnkaywXBtPZdMtTapsYiA6VQUPGTPl4DUDWMSSjeBCLD2Vd7meJHajtWC9q33fY8kImZVIfLMfPnYz8hXMcJ2voanucCmZDCWQToc9OVajj6Vdd6Tng8i4NKwAAAAAS7QmzSPpM6EAAc0D8wYAAJxm3bmxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "portland",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAWddAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsVTO8ky4LDYJjdeMMgm8u2k3WYDa1eQAMemzQBKqi8HFVfh6I5i4EO93W9Tb2t9Xn4WrXLsqeNtai8YQ18HviZii6x1PZXWt87mnI3uln9RfaAb5W30BptIuY3ANJpiz1MFWvmYqIaUJAGw6NSIwJr61Irx47Guy6E2nGwcBzj5oUbzrkewOR+IDW8npaLrt9LC5g2o8iFxqtLQ7KFgaN/79I5/49+NHSSOnl61J1xtWDFr8gyUsZwqxeswJfTJSRn/k/ooxWhSRzZRTVvRURVWcoJrhMGwKdKzDExtdD5ettBDkMm8r7OAzqM/Dk95+UEb0kdRmk3YXSFhnsqG+DDGNI7+7YlY0/TPJPINTW9PD6zKFM1rGocLZUlwkzV3tNbbh6HivJ7nuXPubnav9PBXP0oWh6vBFMTEIVrybvLwSo5c3K4M4lS5CVwAAADoXUl+M7vn+QABgwPYBgAAvyW8+7HEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Rose Pine",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXFdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsRxoMQgbqT4yqrtWs4S5+QQj0fz7PSCY+jcDVJjDdCqSuOc8gbsT8Gjlh98+IhFKzepPPQS8JILf1CaxTngmsI8f+Kxg/HutaZTGH0YihIvq1w7bn7GZNoq+EtFDyz6tN8Nl1NqrjpqSXP6Z2EJZpcOXRN0EB6oSw0deyKQDnOZN+8/bYiFmoe/NRuhlY8bpn/HAwz4LOF3Z9e8TTr3Ur+dt70j78Qrpmz4sO0KIs2kIwE4pezHfHJRXbOqBuah41vJutyjeEVtWbPftTApMz5Lvlp2qgtf0p06Ky2drqiCFnS86ecTKsGVLF04IU7YZfj/IPOD4seGHIVjw1fA/Yl4hO3WOZnQVV3rsIMnrLOFegQsso6CTQpwlUeOLxA0Cz9shmhzd7ovPKVcuYi/gC6eDcc5MxRfSLfGtdzw+xMNMPA8jC6ccd5McWgh6Ni/JsL8BulqrAAAAAC8qyPaDtNOXwABjQPaBgAARIy/a7HEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Rose Pine Dawn",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXNdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPfEPp9UdBOsdANom+oPIyBREMOn3ftJj8q4sLZ3AYHUWvJlDXMAJ9RNTE4isXMzHFwIiIVpqhLSZ1YayQkYKM9/UZWCezrqZCc/ELZEjpoRGUmQOP9z9htQT8B1M5/Yias0IgSWuicj8UBKq+ycQX3QfHDuvKxRivrrF516AC2l1P3iBsr+EPMJX42P6LO2IbJxXREiyNgn+pJEyeJZhyccw7MPuSZZ5wlGzrg0xtwo/e7oFMlw7VUtZx9MrUtfb8N/n51kNzOlmpEsHkWvltxExM8wcAOwKer1h8cQFa29iGPdgtDAgnjwv3L2VsOwYPOdr/41J2fRUeT9rbZ56px0gTps9Y5Ut+BFfIeBSrfpJU4neMxAEGSxVwfrJa/wa5y2zSfAGDBchpxI21EQcgqGI+6oLbXfMlkOhvaaLqYd4DPBQKmNEHjBz0zENXRqwIX9zDhqgIrxCOAAAi91U2UzXVnQABjwPaBgAATy13JrHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Rose Pine Moon",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXBdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdshLBQZQx7yOmn5Pi14Lo7E9JcbIeJSXRvZjMef9fwZz0TZwxa6I2h/yMvbRGLGysAc64m2spubGH+Opb/g4HHw9sb53iws58Cx0HzgIq7uC0Uyb8OzoHLUpwvG05jSpx2U+gNDNl/4jFydKqjKi6Ev2RssbqmiXdiCIXmKmC4AC8sUKEe21cj+XzXpOHX2KHYsiTqtQimd6GErV8fDL4a29XJ+4gzogksP5uHh17U9gZUP9eT0Wg+F1gy4pHcfYn2CHrTlpCX1GMiaD/aw3h/tkQiG3wn/Xlx8AZIj6ffx15ULmIKCPldR2a8gT9HjFH+UIt9K1W+9dOWgvjAs5+dG6ddhGtg5TP9n5EjubU1H4UVHHYWMQv6HuOuuC8+uTBHhVMIUdoKFVbQycjOfrNZk2j7QEr4j0Yibl/8qxy4bkwzdty3UpzY3sDBQ3/oHaAVXwRawZAA45bGsatWOeAAGMA9oGAADhX+OgscRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "Solarized Dark",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAVBdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdmFuozN3JDMDD5rlbqh/AWS6GRAMqZetIc0Jy19UUhEd7xEwVJ1kgAaqeXNZDIJ+RkQM0tuv41pai0DXN8lVhz4lbSQr/plMo+RvSFwJtBu5U8qKbL+hL6HCTrT5PK2qrtCxhiS2jbIed3Fqv6LSrmg9pne+o+JDW4E98tOqLHRq9jjVwfYCkHruAOb86wTtDjzQ8sNg2RcT56YkFE9s93O8+wbfJO/scOvv+yWSOTiucMAlJ8vleyp8IotDXNrJxHgfTuiDWFcoP1YLVKixWs7w7o09bhvBI/eNFmiMCFtbieV9h9eWIpIi8E3Udfbz3UFNPyGAVCvteN5OAi4Z+Bkl9P8lfrbEebMLL6ljYzVWz7+HifOzkSjFVuNjql1wGeE3xlNRlTKcgR75D0Z5BTRvC6JElAAu4yATL28d9gAB7ALYBgAAgLF+P7HEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "Sonokai",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAX5dAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdsifhg9atHGi6E/nWYV0Nrc3RSELTVpRqC8jfb0b9t1FmVFrfyvZnZac03is3NUqeWZCJjRZxjT9vXOwUCqnZK83hn4m7Nni5VxxDMXBj+K/EN9pCmMyXo2NMplLLv8xNBJwp5Hi4QpTivUZ817DX/5uchLHeBmeIYYFa1ZD4e0HbFgafz2cS8mdAS+0O3/s91OIYVo8Xx/JXlcDap9lcvgtVhZDWVV49yO0x2/0G/hhfTYnVD5f5qIwh+3TvaJbDl265AEW6t2nWTX8/WsTxd3CVbEEgmNUuY6ORHRgX8VQFKLjNzcfwqexJyC+v86KviHutqtppIoHtYTrvRwrW03KOZ5K5f/QxumhkIjd7nkLMCR8NLKacxGFGMFnWxGVqIlbmNLR/wArN46U458TKD4C9Uo0oLT1Paxwe6VV84pcbELgTJAtHUYNPZW8XipKLBD2UxyMWuaEzSSQr2y2PMY5bAAAAACcALN2Cl1vSgABmgPYBgAA7HZl37HEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "sunset",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAW1dAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdn68mhHq5bES2sldWbpseF9Dbjjln7a7f4edkMvGBkw2wOYctwC8ec0npvwa5xMpSQ7pno28b6STytlFL1JbN1tZJT/nHPOQ3pwaRa8HNUpxr6i+OIlwW+/aN/0GBcbzvjGSq6v7nMIOsP53msESQbX9OvZVvF/s4n4cAt+kPLfESviWY31aNuH/q0ELiCXf/Ll5QA07FMB3M0RyA6fm9P8681prEIAJZJD4wByOzGS2fIQm9iw6n2Jyzp84XA7NWHLxwmwt8XrFTA9SID8dCaZGQPF3Eoewe11ueU4LASLDEk49jHOfA9fMadJD6gnWpEa1qk9f2sAhA+Ot1b0CsPiIR/dtkesHaMKBDsbhTA3DfStv7yC1Oe3l7oeVrNwNIJV+I14s20A1HsBSs6EwtV+i6WlZwtn8UURTxtkm6+6P1t7r4fGN1H2B6ARONlLbJ/ROAAAAAHQbm92FOw9MAAGJA9gGAADZBidascRn+wIAAAAABFla",
    },
    BundledTheme {
        name: "tofino",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAaZdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdnvR+9n/6BAzP8grEfDdt9/kcpdODK5AhQuZa0xzqMwsLLV/epf2nWHD/aw+aNXqvUpBCPo/mzw93m1bBz9uJEVQ4HMz2CDdNh5zOQDIk1xLhjr8D22x22nv/9NORh/FgYpU4bg1o2lWOGz1pd0YfzDwnaBD/slLJj1X50x4BC+FfCVfhU4symGH/cvOKo95LBSlRZzgHDtDIn3tlIsT8AEOLXrsEBzwkece3FkjSc4Zlz5cKwA872ooKNrhd6z8GgFbJq5IJoiadShTIBjwBnEcB+IdnkmvFdaMCailUZiUHptJSP5IW7nOBVxYmjeigaiF4plyRaAu8X26AVlTRnnuXr/woXiR9juNcrDu+u3oIHa0eB7LTpo3TRvGtYKDv/i5tFErcUz7b9+j5UIOqKpdOCR8VOA5zFuzGUtO9WxUy2ZF9ktKsPH8pgJPo/bUJIjr8W4XItp1hOno1NV9g2VGcUz4UEsydJrxot2fxrdHw769HGDF9cz2aKVoJLhfTzdLT9VBdbQqEwYAAAAAgv2eEtqFUAcAAcID2AYAAHb8uD+xxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Tokyo Night Storm",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANbAXZdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdn6o7FqQQ0nD2U/nWYV0NrFAa0VQHoErzVAzBMaR2rp8GDYSudUC91YzWvCtEHSmvHzPTe4UEDcBQwInjxVPANvFZsksETg4AYj2zpDqvRkm4XWjGICOnf+M+L1IMCrvWDs2RdsPgyW8FHjh65xp4+BmPZ2+l0aH+EohCip0euYQHFlJQn/8xNUSZCzPogfu483KzxKCR4b2daIQlaOTcP2JPQVX8ya72baSo77xRD6IGqk8/MZ4kPM20/8+CyB3fO3GaFZDmtkYe65beYVFW5U+EAeSMdQyxToXfmH/V0N4XDV95uFvNaZkrpsRdnzuhkmc2GcMebk3FVgGzQxcTTcx2XfE2WK7iYtPAak8lDFDJdXqf3CknxcQAhtyRJBZDPv6TBn3F8cIAZzCUAyUpdDUFh/l+Vv564ZdHl22IblZucay3djfU+7SNXqQDQMNCRTUc5eTVFoH3aV7AAAAjnmeKLmo/S0AAZID3AYAANZjVLyxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "vanimo",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAaVdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdshK60TCek+ZTjGJroz9TpTmU6flOEHn1AcVJF3/wPJig0qcIs0wSerc1KTIHklSM53t35CWgLQhNiBuo7DM1oocYkdRqbohXuQBDq/d/Ai3MZawXyJKjNAvZGHxvPbfyJNuyllXzNV6rmX6F+vgpWMbEzyaIPqUHO1wjc9PfysWlE+y2SGUc7S/nbKSmUcCkl3LVp0GKCJGPQ59cVnSiwNWWWTbSI8y3z8QAxGRTjDkNJj0OQ+3PSdUsdgwLYAxmRmH7HI9PuVEiJpHFf6R3RW0Bzpr162KYURCfpS4SZikZHbG4yPrOTzVKdXKbdS+rANez3dc7yMRSNATMKgaTVmaan9rFurxienXoKbRenqI9Q18C/QWEejaRqAFn6XNW7FjcMuowAIr/AC5cjzAwbKhgjtfUSOgC2TKBbtFln7ESaqdE8Hk4hJFhg2iaUF/L9JpyZVU5DEmJ06O6zNOAPpwizU1Oh+Pl9jzb0bmrJMUxmp1LCPKq9p2LmIoJ/mwUOHjR7GzarM8iQAAAAAAxEk7/P6AHIYAAcED2AYAANiOLLmxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "VESPER",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAVxdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdnqu0NAP0TmPs116aA6rS26AKtZ3/oIM7vCqX/3U9Unr8cgYTTKqXSjmKbYYcFtYdi8iL9u731EZJdPPRLxVCpeqVvMMyJR7jf1PJEDEIhQwjllzY871Zpp3Q/W7CE63FkUX2fgx4R4NMqxsNJYon3nCFBp0Go3uX/NDycSPgYDiLilVcCnXNIPeU0BUTUFI9v5T6Uc8PvCB8zz9sumJn07ZI7PPpZ5mmoG1wdwqS8DiX3MgB9kAzA/F5GqbGa5k2ovlnVL6i2WuPkc4j9m4cFtO5RRU5E0pPDXAn6poBjTJ2MjfDyw4VNwmsWBImVNFISIm8uLMPRhyYcDceLPBjwHvEmw9K6nIqyBAhpHnDmfDCYFe5C5PeVyhSm5XVOjR+VitrsTNBK4Bp0f9EEbWsxJfrKyS/cOvW3xAwnkQ+KTsAADU9wX9DrHEyQAB+ALaBgAAhjkwDbHEZ/sCAAAAAARZWg==",
    },
    BundledTheme {
        name: "vik",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANXAZtdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdw39eHNHz4MJ5W5B9Iipeb5JpFuFFPHKN5SPODO31RYeMfWTiFyVkWYRYXomcSTPboyRqcNAGcxcEFfAOcYrtBq1a60IlNnH0Y3NZZbB+0QloHcYCgEM0glPT5RXBSw0ltMQ6Dz+yi5IGUoa3b+yAtABsRRRRje8uw+Cc7NAn9ao39YLweiFFtf2Wq+ivlp4+GT4hdjQf+krFv7eCDqvY9f4ADl0m3evRfvhznXXD8Aq5ZyBYZzz4roj6vph3Ob7Lu/BawiTP2rmQ4dwVkMPaXplB+5QmGvc4ugicw3U3tUm2/nDo4guCefP/e/XY/024zmLZ411lV+yAnaaiMd/yppYqjojC6Kb3rtR0okDBBfGqD9q7tJw6LAz8PNhm1bijptIsgnz4ykuJSMyYx3p2CuhB8SIIo9CoDH44m15VltcupGF1NjlIL8kjXDogEB/D6bGO+jnCTJKUZijjq/Vp/bcL2KrKGBNOv/Y0Z85UuOtP0M2Op8GZR8hYiWXDHuJtgAApe4T/nqEgsMAAbcD2AYAAARgV2SxxGf7AgAAAAAEWVo=",
    },
    BundledTheme {
        name: "Zenburn",
        payload_b64: "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANZAXpdAC2ZyKcQn5i/Wotrh7ZSwKDb81UqcjUTmmcPdw/qK6Rzf6Zo69xBdXB/4JDb5i1KDDYQJBekq/qFP8/ksd5HqGtPdQb7jd3lpza4eZVjJ0w6edgQKpX+YGddeuty3vNOg87PIXVcIRBcNp9ARWcOlXE39ZA/36kuV+jmYFghWriVXb9v8WJ1Xfhpe9mL9J3AGohjVNrgwfLREl93hUZ3pcaVRNhAI/kN5K/gQLfSmMVBUSm9hp7+3e54hCO4qVNwvQu/l/Qoe98i3IPJdOaM3GyGN+BgpnoHB3SLRfZ7sKPTABqNN51x/LUf5HQ8BQLHacNeDzdEh3B6yonbx3QyZ1zkOEs3sdnevFp9VAFq7D1N/f033XvQ2SwlDbWZwYhr6HZDbh2Cc0Guka5sAm/kWqKgV7zbp3lc1n10hQtOPhpN1EGlsIvj1oLbA5T8AMXGttHVe6DLa0R5IZfKaHwOEd3evRj8JAd1yRw+MVt/JQADVHFOfTOnvvLWPgAAAJdUkbSuDVXkAAGWA9oGAAAcfq4CscRn+wIAAAAABFla",
    },
];

/// Decompress every bundled theme into `(name, toml_text)` pairs.
/// Intended for the one-time `ThemeManager::init_themes_dir`
/// extraction. Do not call in hot paths — each call decodes
/// ~50 KiB of LZMA data.
pub fn bundled_themes_decoded() -> std::vec::Vec<(String, String)> {
    BUNDLED
        .iter()
        .map(|b| {
            let compressed = base64::engine::general_purpose::STANDARD
                .decode(b.payload_b64)
                .expect("bundled theme: invalid base64");
            let mut toml_bytes = std::vec::Vec::new();
            lzma_rs::xz_decompress(&mut compressed.as_slice(), &mut toml_bytes)
                .expect("bundled theme: invalid xz stream");
            let toml_text = String::from_utf8(toml_bytes).expect("bundled theme: non-utf-8 toml");
            (b.name.to_string(), toml_text)
        })
        .collect()
}
