// @generated by scripts/build_themes.py — do not edit by hand.
// Source: 50 themes in themes/
// Regenerate by running: python3 scripts/build_themes.py
//
// Gzip compression via Python's stdlib `gzip`.
// Decoded at runtime by the `flate2` crate (GzDecoder).
//
// The default theme is embedded as a Rust raw string literal so the
// published crate does not need the source `themes/` directory at
// build time. All other themes are gzip-compressed in the table
// below and decoded on first launch.

#![allow(dead_code, unused_imports)]

use crate::error::SnipResult;
use base64::Engine as _;
use std::io::Read as _;

/// Uncompressed hardcoded fallback theme. Embedded as a Rust raw
/// string literal so the binary always has a usable theme on the
/// very first launch, before the user's `themes/` directory has
/// been seeded from the compressed bundle. The original file is
/// `themes/Cyber Red.toml` — editing that file and
/// re-running this script will update the embedded copy.
pub const DEFAULT_BUNDLED: &str = r##"[general]
background = "#0A0000"
border = "#E41951"
horizontal_rule = "#3E0101"
unread_indicator = "#C1DEFF"

[text]
primary = "#E41951"
secondary = "#8F1134"
tertiary = "#7D3F50"
success = "#D7053F"
error = "#C1DEFF"

[buffer]
action = "#5BA4DB"
background = "#090808"
background_text_input = "#160E0E"
background_title_bar = "#1F040B"
border = "#000000"
border_selected = "#E41951"
code = "#EA9995"
highlight = "#122C38"
nickname = "#76ABEC"
selection = "#73000054"
timestamp = "#750D2A"
topic = "#E41951"
url = "#FFADAD"

  [buffer.server_messages]
  default = "#5BA4DB"

[buttons.primary]
background = "#000000"
background_hover = "#4B0A1C"
background_selected = "#230202"
background_selected_hover = "#1C0606"

[buttons.secondary]
background = "#310000"
background_hover = "#610B0B"
background_selected = "#701414"
background_selected_hover = "#882828"
"##;

/// One bundled theme: a name and a base64-encoded gzip-compressed TOML body.
#[derive(Debug, Clone, Copy)]
pub struct BundledTheme {
    pub name: &'static str,
    pub payload_b64: &'static str,
}

/// All bundled themes (excluding the default). Sorted by name.
pub const BUNDLED: &[BundledTheme] = &[
    BundledTheme {
        name: "acton",
        payload_b64: "H4sIAAAAAAAA/5WSy47bIBSG9zxF5O5H8Q3Mogvjy0tEkUXwSYLGgQjwqO3T98TEM3XVqTQLL/z/5/pxDhcw4OR0JCepXi/Ozmbcfd8l3/I+T+k+ISfrRnCLxHKaVW1CrtbpX9YEOQ1unmDxSlamrEvIbBzIcdBm1EoGGxPrilKOtcghwI9wJHenb9L9XLyONbTFRA/KmnFVm44xjq0CuKBXsW14L3oMnZUC76NWVqwWCQHnns1WhRxO8/kM7kikCtqaaPY1b6rk72WzJqXFRh4ek+Ia9zlEHCITpdhG6DDBcJKxbcHznrYbXhndt8U7wsHDBCpA7CgYrXiaEGXHCLBr2qbD5a76cp3wi20LUWQMSxitXo28xdCW80LQB7JHwXW1Mi8aViMyfQMf5O2+qJXAxRBvsHetNghmNy3//b6re8wju92T2IsH94YDYx0vL+CPaI1wlvMUNhUehEOwxr88H/TzI/qgdrVvTzw5y8qSbswNoqxPcc9/+n9UWSF/DPN+SV8bZ73gz8ZZr///43BOywqf8Tfg/euOWAMAAA==",
    },
    BundledTheme {
        name: "bam",
        payload_b64: "H4sIAAAAAAAA/4WSwW7jIBCG7zxFxN6rAsbAYQ92HL9EFVkETxJUByKMq3affrFJNs22UWVx+Wc8888383IAB0EPW7TT5vUQ/OT61e8V/kVaygnFaOdDD2GRmChqUmN09MH+8S7qoQvTAEuMClYQjtHkAui+s663Rkeff6xYUatnjNBLhPe4RedgTzp8LDHJa140GI1gvOuvKueCU4lRhBDtVSypFLRNqZMxMI5Z43LNCEYQwqVZTblU7dxsN+33ELZIm2i9W4INk2Rd4C/DKiIJ+Sx3s9M0xnmKOWNN2v8zbByg2+ncllZMkPKOV6pa3hB2IwxgIuSOqi2kXGNkfJ8BVmpDRbJ9tIfjkF5uyxRR83jOmlenTzl1w1XTVDOyueB1NMrZM0mjRXuCMerTOYOkglKRVH+2ZlGEqsoiLWMKQ+a1aZsqbQ6tVhdiTyOEt2Q41Rn1AcZtCvWw19MQ7yDOhGP0bny6LPTxEd2oHf3bFc9XpHeISJW+7+Ofq1wg38z8u6Tv7JQP7aTzrUj72E5Rl4Kyn+xwJWqadvMXQwbdHlgDAAA=",
    },
    BundledTheme {
        name: "base16-atelier-forest-light",
        payload_b64: "H4sIAAAAAAAA/7WSwW7CMAyG73mKqrsjCl1LDzsACy+BUBVSAxlt0jkO2vb0SwsFso3jKuXQ3479+3PWe9CAot6wrZDHPRqnq+glip9WCV9xHrOtwQqwl5JFUiSzmB0Mqi+jSdQluhr62Hw2T4pVzJxGEFWpdKWkIHO+uJzO0u4iWxN80Ia1qBqBn30sm2XJs+9jQRpdDWqeZTxbxIwASQ3iUMY6KcHac+KiyCdZzADx0mw1mSzTcdds63Y7wA0TkpTRQfqjYa9y2Tn1Y7SO+gye8QkfhxmKaii3AsOEG69iWaRFMkilhRokQRWwlKY6A8z8x+certofan/CtlrJoxbNOXX6WuSLjkNfcBht2ACpBiyJpg3wkmmVDNA6rPv/dJxznnteUXQhNrKAJ2/Y17FiD3bjQ29GhQSjqBVIAfEoenfqp1TBTriaAuPdaoiMtqPLS3j8+m64D+Z04TpMehcM2F65/47fVRk43Mxcn+AvO39s/7/sfAPqC6SGkQMAAA==",
    },
    BundledTheme {
        name: "berlin",
        payload_b64: "H4sIAAAAAAAA/3WSwW6rMBBF93xFxNtXxjbgLN7CQPiJKkKOmSRWiR0ZU7Xv698QkzaoqZA39w4zd479egILXg375KD028m7yfabv5v0T5ZRQkWaHJzvwUdJcp6jdHbe/HM2qKHz0wDRY7RldZpM1oPqO2N7o1Vw8UdRc0LRTF4DfIR9cvXmovznzcsryZsqTUbQzvZ3lcqiEU2aBPDB3EVGBZEFlk5awzhGrRC5xELwfhm2rXnLmnnYYToewe8TpYNx9mbWvMwLmf5YluLHH+VuToprXKew4MgkJesKEwboDmqBwxlhuzWvnOzIl9SNMIAOECcKwZoZr3Z9BChK2bQY4WxO5wFPHMuqLCM41hr9ZtUlljaVqASfkc0N76tllNYMOwZzgTGoyzWCFIUQyCy4q9E3hVfbqkY+kx8ir11F2hZ5bTYLsZcR/DsGxj6jOsG4R6uHo5qGsII4Ew7B2fFludDfH9E3tbN7v+P5iXSFCH2WlU/9xy4L5O8wXy/pWZyMyl/iUJLT9dNYx6E835XP/ccudcm2eDf/AaNANFVYAwAA",
    },
    BundledTheme {
        name: "black but with important highlights",
        payload_b64: "H4sIAAAAAAAA/5WSy26DMBBF9/4K5O4jaB6kiy5IU34iQsiYSWLF2MiPqO3X12OgCVVbqXPEgjtmZnyZwwkUGCYr0jB+ORntVZs8J/ThcYVQ0mjTgonSOkcoOWsjPrRyTNbGS4i5VYZQ4pUB1tZCtYIzp4cP8xiUkIODN1eR3oiOmfeY26cIJRa4Vu2kbkuEEgfGiUks9kg46jkHa6P2tEMoAWPGZpNCDo0/HsFUhHEntIrJ3Rqh3y8bZ9jfyzVOGq7RezfYkSLzE8JJqBs2tF1myMyvNMYk1RYkcAdDx7xEKOG6HQx8LZBgrjidZXiGtul2VWxCCSX4RbFuOFqsEbQMC05XW74gwTLRgXWs66O6yZGg6l7wmQXeyPhexgh+Jcno2MKCuYaBQx3LTmCrkGrhyLx0swrosHNa2cX4Q39foptrZ30d7cl2yCw5syiL8WP+rspk8m2Yr0363zjTBv82zrT9f4+zKRFKPgF4d6VPWAMAAA==",
    },
    BundledTheme {
        name: "Booberry",
        payload_b64: "H4sIAAAAAAAA/4VSwY7bIBS8+ysi976yMRB86MEG8xOryCL4JUHrQITxqu3XlwS7jbtdLRIHzxvPmze81zNY8Go8ZEel387ezXbYfd/l3zBBjNR5dnR+AP+ARNvKTubZxXnzy9mgxt7PIzxqBFeIxtpsPaihN3YwWgWXfqxoKxnNs+w1wI9wyG7eXJX/mUQZZ7LKswm0s8OKNqKmbZdnAXwwK9hxLtomUmetYZoSsZCIxb7g/dJM4j2j7N7sOJ9O4A+Z0sE4mySY4E2R/zts1SCE+TPc353GMW5zSIyyFLjcMkwYoT+qdUZU4P0mr2I5K9hPMIIOkHo2uCm66FO7IUXIHyfGa86XMd7UmGKC78Fao9+susJm6iS4DkcKXFMRQzNXmIK63h4oK6hgd9TdjN684+zHxEC84/E72+2WzF4m8O/RcNSZ1BmmQywNcFLzmExJyUUpUsYhODu9LE/6YY2eMvib3MW9LxFhiTpKNsVNSHGtSsr/W39SITQuX/ds5882fTBUSURJ9ZkdjGrSfG6HkT2qq6/s8LJhIrJ+A8jajmJcAwAA",
    },
    BundledTheme {
        name: "broc",
        payload_b64: "H4sIAAAAAAAA/4WSzW7jIBSF9zxF5NlX5sc2LGaBY/slqsgi+CZBdSDCuJqZpy/+a5u20Vhi4XMv5x4+eD6DBa/6Azoq/XL2brTd7vcu+UVTUuE6QUfnO/CzlPGM0ixBF+fNP2eD6ls/9jDXGKYVKRI0Wg+qa43tjFbBrRtZIWSeIPQc4E84oJs3V+X/zrW92FORJmgA7Wy3qTwrqiyqAXwwmyikwPnUOmoNwzBrMhU8j5nA+3VYzrko6TTsOJ5O4A9I6WCcXSxK2VSx+OWwuMYVLj7L7ZQ0HuM2hrmDcJJjed9hQg/tUS1jWcZSIu54YYEl5pvUDtCDDrBMZE2RSZIg7boFYL2vRRl5X8z50se1jMWM1CxaWKNfrLourSXfs5pNyCbD7Wi0ppJEEsFcYQjqeltA4kKyaBvczehld1lSHimOvp//m/hVMTja7VZiTwP41xg4+gzqDMMhljo4qbEPdxAnwiE4OzytF/r4EX1Qu7jXFc8PSO8QkRQ3M77v9U8uG+SPMO8v6XscQhrcPIiT8xzT+nGcIstrlv8vDi85zeItvAGgLJu7WAMAAA==",
    },
    BundledTheme {
        name: "Catppuccin Latte",
        payload_b64: "H4sIAAAAAAAA/3VSy46jMBC8+ysi9j4yCThwmIPx4ydGEXJMJ7GG2JFtRrv79QsYdoZ5IPlAV3V3dXW/XMGCV/0JnZV+vXo32G73vMt+cSawqDJ0dr4DP4dqRnGDM3Rz3vx1Nqq+9UMPM8YYx5xmaLAeVNca2xmtokuJVXWohcwQeonwO57Qw5u78n9mrGCFJHWGAmhnuzVKGJFVmaEIPpo1uJYJg9YQQkrHFO+bDIH3SzO+x/JQT83Ow+UC/oSUjsbZGZSCFHikfxpWEDFXfg+3k9JxjMcQE0PKXJZbhok9tGflt4R3v7YWtgF60BG6xa+mmjpq1yUDj/vqKPlorrne+vGltrxkszBr9KtV90TFBS1FOVk2FVxHa0rGJgHR3CFEdX+knQmaN2SMuofRyUVWSZqPm/L9/J8LQqY8tNstjj0F8G+j4LFOUFcIpxHq4KKGfhElK5Hz5HCMzoanZaFfjggv38a3m3tbDSK8FvkG3JqUs4LRb/EPVZpjQxn+KOf/LX0RJA7iKPhPckpec/GzHF6w6tOVfCOH7Wkxsf4BNweHi1oDAAA=",
    },
    BundledTheme {
        name: "Catppuccin Macchiato",
        payload_b64: "H4sIAAAAAAAA/4WSwW7jIBCG7zxFxN4rG7CxDz1gY79EFVkEkwTVgQhwte3TLzFON1a2WkscPDP88883vJ2UUU5Me3AQ8v3k7GzG3esO/sqrvEYlBAfrRuWWUNlRXHEIztbpL2uCmAY3T2rJIYIoZhDMxikxDtqMWopg08W2ZFkftcBbUL/DHlydvgj3mXKM476AwCtpzXiPsoLxtoEgKBf0d+kq42cplfepsOSsjteVc2uzjle0Xpod5uNRuT0QMmhrlmRfsJr28GnYDmU4ewwPN6dxjOscNvM9VugwqeEg3LbgL68twsGrScmgUkfSkrzEEEg7JoANbXhfRbj6dJ7iSW2LmrQ0Shgt3424pNI657TDN2Q3wftoqMWIRANBX5QP4nJNAk2Z3QSCvWq5RKqsogzFTbkp/TPGexJ57XYrsRev3Ec0HHW8OCm/j6lRHcU8JVNdx0ndJ8IhWONf1oU+PaJs/TbczvbjDqjLe7TZxhYSQgjj4p/5BxVEUYX5o53vt/RkCNWoJegHOxjhosh+tkMYyUr0PzsVp6TJIfgD7LWIsloDAAA=",
    },
    BundledTheme {
        name: "Catppuccin Mocha",
        payload_b64: "H4sIAAAAAAAA/32TzW7rIBCF9zxFRPdVjR0bL+4CbPMSVWQRPElQHYgAV22f/uLg9Mb9uUjezAxnznyDn49gwMlxh/ZSvRydncyw+bPBD9l8OEZ76wZw11DZVE+0xOhknf6wJsixd9MIqbzLOtJhNBkHcui1GbSSwaaLDWelqDBCzwHewg5dnD5L955ybVuKAiMPyprhFmUlaxuKUQAX9GfpIuMnpcD7pbDLWYYROLc0EznljM7N9tPhAG6HpArampRkPKdR4uuwNKNkex/uZ6dxjMsUVvPdV+gwQr+Xbl3wj9caYe9hBBUgdSyaIitzjJQdEkBe8VZE2yd9PI3xS223ddFUEbnR6sXIcyqlddt0fEY2C95GI01OChaR6TP4IM+XJEC3EVGM2otW10glaFE3cVNuXNR4IeI9tNksxB49uNdoOOp4eQS/i6kBDnIakylRd4SJRDgEa/zjstBvj+hpOStuJ/t6A8QyRupVcgXpylT8mL9TIfHk5b2dz7f0zRDJST7X/miHcMIL8rud287+b6ek22r+S/4CdPLS/FoDAAA=",
    },
    BundledTheme {
        name: "cork",
        payload_b64: "H4sIAAAAAAAA/4WSy47jIBBF93xF5Nm3zMMPFrPAJv6JVmQRXElQOxABbs3M1w/xY7rT6mgWXvhWcevWgdczWPBqPKCj0m9n7yY77H7ush+4IAJXGTo6P4CfJVKwjvAMXZw3f5yNauz9NMLS3lCO9xmarAc19MYORqvoloOsLaXoMoReI/yKB3Tz5qr877lW1w2v8gwF0M4Om0pFxWk6EcFHs4lM1JI1qXXSGkKYtSLntEjHwft1WNFVssX3YcfpdAJ/QEpH4+xc5FQwmWJ+WTbvcIPJZ7m/J01r3Ka47EcIxeyxw8QR+qNaxmJJJckfeOUSV7PrLPUBRtARlomMl1yIDGk3LAAbKcu6TXDN+TKmbx3bEM5ohqzRb1Zd19a84fs7h9lwWw0LWuJkEM0VQlTX2wKyrgoqk+puRs9KRYUs0yaTH+d/2exLntzQbrcSewng31Pg5BPUGcIhlQY4qWmMDxDvhGN0NrysF/r8EX1Qu7j3Fc83SB8Q4Ry3Xy5lq39y2SB/hPn3kr6L0+L6SRzSFpLmz+NQUgpa/S8O3VcdS3H+AsjvqgVYAwAA",
    },
    BundledTheme {
        name: "Cyberpunk",
        payload_b64: "H4sIAAAAAAAA/31SwY7CIBS88xWmezdA66qHPaiVnzBNQ+mzEhEMULO7X7+0tiq7uk04dN5j3szwdg1osFwVqOLi2FjT6nryMUne8ApvSZagytgabA/RbbrJlgk6GCu/jfZclbZV0NfImjA6T1CrLfC6lLqWgntzvYgxY3m4iHYePn2BzlaeuP3qa+mSsW6OA2F0PaIYrxljCfJgvRxBxjqi0NoKAc7dqJd5gsDaYRhj2SbbdMOqdr8HWyAuvDT63h6U/Dab417EHS47pcHGufVXf4TMyCbukF5BWXEbBfCQFx6+ESwdKBAe6igUYWqIkjjI5qDCuQ5erDFerBOkpThqfoI4iZ5wNEdWZEtnITR5Auf56dyj73jeE3hzliIKt7Uq+keTyZDZ1IG9BMGBx/EGXBFKNex5q/wwP593vrqMvTfaTYcnfb1G99wO5jIERHKaUhYV44hyQsniaf2RJSMrSh7F3Hbpj5zbKz2TQzO6StPXcsb9/19Ousxms+D4B76dpS1aAwAA",
    },
    BundledTheme {
        name: "Dark Green",
        payload_b64: "H4sIAAAAAAAA/31Sy26DMBC8+ysQvUfGhDwOPdCE/ESEkDEbcAM2sk3U9utrJ5DipikrDsysZ2fHHGsQoGibo5Kyc63kIKrgNQhfMMEHHIWolKoCNUGZgxqp+JcUhraFGlq4ctFumURpiAahgFYFFxVn1MjbwcPbMsEkROho4MPkqFe8o+rzymVptt+sQqSBSVFNKCZpFlnUgDL8N6gHxkBrDwOlxmHZFsc4dsPK4XQClSPKDJfiSsar3XqXhA/LJhFxZ37gwjm1a/SD8Xafd3DTQlFSP5x5XmmU4nSCCg0tMAOVlxeTFXiLNLxuWvvexpJtvCK2TXB2FrTzW2+C99WSeBO7yHgH2tCu94OUPWceMqjW+0ZBMCa20KAu1rDV0bQGnVvqXfLbGDw+oQUrONGhNb6MFTFGCr0Yb/nxz7orzMJs5GVMLdq78kgvObJ29Sc/U4lXruZ27j/YgyGydPXEDtm4em5nusj/7Uxd32fncsBvAwAA",
    },
    BundledTheme {
        name: "Discord",
        payload_b64: "H4sIAAAAAAAA/5VTy5KbMBC86ysoct9yJPE65IB5/MSWi5KlwVZWSESITTZfH2Ega6h1tnLg0t3M9My0ni+gwTJ1QmfGXy7WjFoE34LwCzkQTOIQnY0VYG8QxphgD12Nlb+Ndkw1dlRw4yihEc1CNGoLTDRSC8mZM/OPdVLHdRIi9Ozglzuh3sqO2bcbVx7LoqxDNAA3WqxoVmRljkPkwDq5gglO4qT00pFzGIYbFh2yOvZ9wdqlWRHTOsJTs/PYtmBPiHEnjd502w+bkIxU93AzOfVj9KOb5ztQOs13r5BOQXNmdiu421dFCElXqBlAAXcgNnJuBGycXeXlqvzn1rUeyDFEWvIXzbpZeowKXNNpZVPBdbSvKalyfx0nOxgc6/rtIk0v+abRaNXsMs/z2rtEQbBs7GkA++oN+zoDu8Bw8tR3I+c2aZXhzN8yCHpm3Q76Mco91BktfQ5ANEYrqeEx3bYf8H6SKRWisdCrt6ZlUv1b8ZPZvdGdQhu37yKgZaPaWp/y45zRw9MS18dP5D0TV/O6HN9TEck35CYAJCclxR/y91UW1buZv+/kP+1MhchjO0mVVkXxmZ2Epvjos/IHGfWHRzYEAAA=",
    },
    BundledTheme {
        name: "Discord (80_ Saturation)",
        payload_b64: "H4sIAAAAAAAA/5VTy5LbIBC88xUu5b7lBazHIQdZj5/YcqkwjGyyCBRAm2y+PujhrKVaJxVVceluTfcMw8sFNFimTujM+OvFmkGL3ddd9IXsCSZxhM7GCrAThDEmOEBXY+Uvoz1TjR0UTBwl9ECzCA3aAhON1EJy5s38Yz19EUIvHn76E+qt7Jh9n7jyWBZl4Bxwo8UNzYqszHGEPFgvb2CCkzgpg3TgHJybsMM+q+PgC9YuZkVM6wMezc5D24I9Ica9NHrltm02IRmp7uFmTBra6Ac/97endOzvXiG9gubM7FpwN6+KEJLeoMaBAu5BrOTcCFglu8rLVYUz25KKPtNjhLTkr5p1s7SOj3GRjSMbC95ae05JlYfb8bID51nXrwdpeslXRoNVc8o8z+uQEu12y8SeHNi3EDjUcewC7hSob0bONmmV4SyJAtQz6zfQ90Fuoc5oGfYARGO0khoe0237CR86GbdCNBZ69d60TKq/K34wuw26UWjjty4CWjaodfRxf7w32j0t6/r4iXzsxNW8LZcfqAPJV+RqAUhOSoo/5e+rLKqPMH/eyX/GGQuRx3GSKq2K4l9xEpriY9iV3+j5dEM2BAAA",
    },
    BundledTheme {
        name: "Dracula",
        payload_b64: "H4sIAAAAAAAA/4VSy27bMBC88ysM9R6YD70OPehh/kRgCDS1tonIpEFSQZuvz0aSEyt1Wwo6cGa5Ozu7zyew4NWwJwelX07ejbbf/NwkP1jBKp4l5OB8D36CaEslyxNydt68ORvV0PlxgIkTQuRplZDRelB9Z2xvtIpufpixnFUiIeQ5wq+4J1dvLsr/njhZ4McSEkA729/QnOV5iS8i+GhuYN2WXGKNMGoNIUxYupVVXicEvF+KSZni+Sh2GI9H8HuidDTOLmRdZE3yvVnsi7H2Hu4+lGIb1zHOERWtmVhHmDhAd1B+HfDl13Y5N7ALMICO0K+Ua9fDoi0vG3T8bE7nAf+5MKvZjmPT1ugXqy7r0DnhrTme8lLgfKK5QIjqcp3Qkpas5Ii6q9ET0mwbWkuclR+me1HvSondk81m8ewpgH9FwZgnqBOEPVI9HNU4zKIklVXRzB7H6Gx4Wkb69zX68u3sXheDHpAri3jL25Q+5O+ycMqpoPdiPnfpTzmLmw/lcMYzIf4hp0Z+9z85aSaqHBf6HZYJ7ThaAwAA",
    },
    BundledTheme {
        name: "ferra",
        payload_b64: "H4sIAAAAAAAA/4WSwW6jMBCG736KiL1XBowdDnvAMbxEFSHHTBKrxI6Mqdp9+jUYdsNuqiJx+WeY/5+Peb2AASf7IzpJ9XZxdjTd7ucu+ZHxrMxEgk7WdeBmiTSEkSBdrdO/rPGyb93Yw1zLsxznJEGjcSC7VptOK+lt/LBpKsyqBKFXDx/+iO5O36T7jLX6IHiWoAGUNd2qVnxfsTJBHpzXqygYF/XUOioFwzBrPOW0LBIEzi1mNaacFZPZaTyfwR2RVF5bs2n/d1mSZRl9lNspaVjjPvq5IxUpT+tth/Y9tCcZbcMAnJENL7w8q9gO0IPyED2ZoDULnsp2EWHV7EXZBLz6cu3DG40Jy5s8jDBavRl5i60N5fRQTtCmgetypMgFSQM0fYPBy9t9Vum+oEUY4O1dqw3c0fWRa1iuDh1ot1uYvQzg3kPgMGeQFxiOodTBWY59DNUUgtE6MvbemuFl+aVfn9Ffblf7vgB6gn2D6An0tf4wBQt8wOIxzJ9b+i/OeqZP4+R1fpj4fRWHYpoWxXdxaMNSGmj+BlWoHipaAwAA",
    },
    BundledTheme {
        name: "Ferra Light",
        payload_b64: "H4sIAAAAAAAA/4VSzW7jIBC+8xSR917ZTsDmsAcb8EtUkUXwJEF1IAJc7fbpi4PTxt3uriUu34xnvp95PoEBJ8c9Okj1cnJ2MsPm5yb70e0EEyRDB+sGcDeIc56zOkNn6/SbNUGOvZtGuNUE5ZSJDE3GgRx6bQatZLDpx65r8qrJEHoO8Cvs0dXpi3S/bzVSY4LzDHlQ1gx3tKloTYsMBXBBf4BbXDIcWyelwPsbVu1qUvIMgXPLMt7hEot52WE6HsHtkVRBW7Nq/yq2EISLR7ifmUYZ1ykkfULkHK87dBihP8i0VnSi5PXKr3z57mDvYQQVIO1kVUvbKFHZAVbyzvp0HuMLSw6csCpDRqsXIy+ple2iDjabNg+8ixOEEbaNpukL+CAv1zR2jiaODfaqVULaOvobs3JjimBLch6jRpvN4tmTB/caCcc5Xp7A72NpgKOcxkSKFXRbVMnjEKzxT0ukfz+jT9/O9nUxKNqO+SqNtUWi4Q3Pv60/TInRYUYfyXzc0h90ohd4PuFv6fCOlc0/6HDKi7b9Hx1GGW6iN+859XRFWgMAAA==",
    },
    BundledTheme {
        name: "Flexor Dark",
        payload_b64: "H4sIAAAAAAAA/31Sy26DMBC8+yuQe494Qw49EEh+IkLImA2xQuzINlHbr695OAlNEyQOzC6zM7O7b4GDJF2JakJPrRQ9b5xPB394ubfxMoxqIRuQIxSEQRB4GB2FZD+Ca9JVsu9grPmpn/gxRj2XQJqK8YZRosX0Y5Elrp9jhPYavnSJLpKdifwea/k2L/IAIwVU8MaiaZJGqYuRBqnZDdwk2zw1rT2loNTcuM6CNUYgpR3mhUXoDcPq/nAAWSJCNRN80f7XrOvu3N0jXA1KjY1Lr192MN1BVRO5bLjn5c6PBSsFHVAN08woieLIGKeigYW9I2uPnXmnwUHmF26IEWf0xMkZ5tCiYp0MoQ2E1pzdj2ZnUJqcLyMa7+JtbCxrcWF0EW4vu/E7DNJoszWJOc6c2UqBvBrBhkeRFlRpSg0cSN9Nogo3871oylhrwdVqXunrM7rndhTXOSB7NA/FRURv6g8s1vZdzO2WnuT8w/hM9EqO3dh7OTbvX8gNe8haAwAA",
    },
    BundledTheme {
        name: "forest",
        payload_b64: "H4sIAAAAAAAA/4WS3XKCMBCF7/MUDL13JPwELnoRfnwJh2FiWDUjJk4SnLZP3yigYm17wQW7yznfnmW9AwmadTXaMH7YadXL1nv3/LdghUmQ+2ijdAv6WoryZBmFPtorLb6UtKxrdN/BtYeLsMKxj3qpgbWNkK3gzKrhQxrmVVr4CK0tfNganbQ4Mv157ZVpGRWpjwxwJdupSqOsTImPLGgrpmJBCkITN9pzDsbMpEHr0SxfJUFCL2abfrsFXSPGrVByNv607ER/LzcXUrfGqbfDxBLnQTWfELaDZsMG26DE8S95DaXGQAfcwuCYrjJCMh9x1cKIXUQ0cuGK3b5zz2Cb5GQZO14p+EGyIzxFdhGcVgvLiIZubyuOYCw7ngYfmlHiZK06CT6Lttfd9T2jaZE5NeR5Y2ILA/rsgJ2OYTswtWu1sGV9N0BVtEjImLC1SprFeNDff6J7ant1HuPBMa4wnjVnEb04ytR/UAlJlIXBI8ztT/qBczvIK5y4InH8Bw4J0ixJ/sOZ7voNHzrIuFgDAAA=",
    },
    BundledTheme {
        name: "Gruvbox",
        payload_b64: "H4sIAAAAAAAA/4WSTW6DMBCF9z5FRPdRMBjMoosA6SWiCDlmQqwQO7JN1Pb0tflpoGlVRiyYZ2befON9AxI0aw/oyPil0aqT9ep1Fbxg6iNAR6Vr0H0qwzRK4wCdlRafSlrWVrprodeiIqJREqBOamB1JWQtOLNq+DEPE0ydiPYW3u0B3bS4Mv3Ra7u8zHMcIANcyXrKbmmWUdfKgrZiSk5lTMc5GDN4olkabgMEWo/NigLHYembHbvTCfQBMW6Fkr1YJqTc7IKfw4Yl3uBwnq68UzfGrbNLHLMTwrZQHdnQNnzDYV/iwWszPlOyMtACt1AvaHJVDwgTmpXEjXIWzbl1r12AlYJfJLsOR+mu2KSFh+YLTsNFZZRFqYMmrmAsu96GsgkpiEepboIvOne67b9jQgl1s6HVamS2NqDvzrCrY1gD5uCkGk6sawdTZZplfljP2FolzXpc6dM1mjF4kDur+4gI73wsxAWkCPv4VZ9VcWO7mNv5vk3P9xrjBKd/2SF4i/O/7cShW0f6nx2yJTh2i/wCJLDHvFwDAAA=",
    },
    BundledTheme {
        name: "Halcyon Dark",
        payload_b64: "H4sIAAAAAAAA/6WSy5LCIBBF93xFKrO3TDREF7MgD37CSqWQtJEyQgqINTNfP5iHGnVWs2Bzu7l9+8CuBgmaNQXaM36qtepk5X16/kewDFZB5qO90hXoXoowjjfUR0elxY+SljWl7hroa2EUpuuljzqpgVWlkJXgzKrhIqVpirGP0M7Cly1Qq8WZ6e++lsVZmoc+MsCVrCZ1g7dREvvIgrZiEtMVwdTNNx3nYEyvJSTHce4j0HocllOcxKvrsH13OIAuEONWKDkmIXnkfJ+XJQEN6aNcXpO6NdrOzvZ77BC2gXLPhrEBDkhIZrxurr1UGmiAW6hmu3BVwUw4ivrYuGNnyKXgJ8nOQ2uUpjTHV2RXw2m1KaEVZzCWnds5SNUK3ivblKyTjXsp3QwdhGR07Xh53khsYUBfXGDnY1gNpnClCg6sa+wIMYs2y4GwtUqaxfigf3+iO7WjusATsXtxhugN8qn+xuUe5vaTXuO8TrwbTaj/F2dy+QWrA/RrWAMAAA==",
    },
    BundledTheme {
        name: "IntelliJ Light",
        payload_b64: "H4sIAAAAAAAA/7VSwW7DIAy98xURu1d066LssENbmp+oooiA26AmEAGptn39ICTt0Lrj/JTLs2M/P3w8gwLDugo1jF/ORo9KZO8ZfiqnwKjRRoCZqF0ZgFGrjfzSyrGuNmMHU+5AAjAalQEmaqmE5Mzp+CMhBaUHjNDRwYer0GBkz8xnzBUBGFngWomF3aw3dLPGyIFxciHLkvjwpSPnYG3UROh6u8MIjJmH0d1rkZMwrBlPJzAVYtxJrWYlOd3v8Z/L3ug6KPVrDKOLFSQgrZCug7phJi24+3XIAxaqttABdyASv7gWkGzcynPb+S+O3fsIwpTkF8V6SOyMDZfVtjl9DqVO9mAd64eJndz1c5weJE8GjaZLLEFZNju2smCuXrDvY9kZbOVTAk5s7KKol+KtpHl02Dmt7Gp+0F9HROZIfGv1dTaI5gFJ8qFJD/I/uixVdzm3W/r7qv9fzjd33ZkaWgMAAA==",
    },
    BundledTheme {
        name: "Kanagawa",
        payload_b64: "H4sIAAAAAAAA/31Sy46CMBTd9ysMszdaoMBiFjzkJ4whpVyhEVvTFjMzXz/Vgg7jg6Sbc2/Pi25bEKBov0M1ZYdWyUE0i8+F97Eu1yWOPVRL1YC6QjjFqR95qJOK/0hhaF+poYfZbBAKaFNx0XBGjXQXkzAqM8uFtga+zA6dFD9S9X2dFXkRZamHNDApmgmNcLQmiYcMKMMncKLRA2OgtcPiLCO5h0CpUWwTkDgiF7F62O9B7RBlhkvheMssyK3aq7A3uLo4tTFOg7lu+MQnAZlvcNNDVdN5OU/6clCloQdmwCnGWRpkKw8x2cAsXMfbrrfHyeIiKImlEJwdBD3CLLMjnKJNaoYfQRt6PLnAmyQvLK2RJ87c7TzNLhUMqp9toMVibGypQZ2tYcujaQt6Z0cN7OnQO1MFtncS17AxUujl+EMfHtFq/Ga9dfL8v6D7cFYSxj4OkqfzvyxjR3c7t7f0YAiHOPTDV3YKSxW8sTMKvbfjpyEhtt9f2W92xloDAAA=",
    },
    BundledTheme {
        name: "lisbon",
        payload_b64: "H4sIAAAAAAAA/4WSy27jIBSG9zxF5O6rcLENiy6ILy9RRRbBJwmqAxHG1cw8/eBgt43aqAsvfG7/fz7O6wkseDXs0UHpt5N3k+03L5vsCRPCaJmhg/M9+BRqWV7IDJ2dN/+cDWro/DRAyuUUszpDk/Wg+s7Y3mgVXGrkLS9zniH0GuBP2KOrNxfl/95yYifbmmZoBO1sv0YZL7cijgvgg1mDxZZT2cTSSWsYxxTjXOxiO3i/iMmt4EU+ix2m4xH8HikdjLO3ZCUqKrbZ92WxIPhruJudxjWuU0gVGLekua8wYYDuoBY4BaWsvefFMMfVGupGGEAHSIp8x2keXWrXJ4DVriZN7D+b03mIX5KlDZUkllmj36y6pNK6qaWsZmTzwHU1zEjDIuRgLjAGdbkmkLiQIj5jcFejk7KQpIp1kx9u/03R5G0URpvNQux5BP8eDcc5ozrBuI+pHo5qGsIdxJlwCM6Oz8uDPj6iT2pn977i+Y70DlF8FEnYj/mvUxbIn2Y+LuknOzmVD+wQmdOyfmyHFvH+qt/ssLbMJcnQf/xqN+5YAwAA",
    },
    BundledTheme {
        name: "Macaw Dark",
        payload_b64: "H4sIAAAAAAAA/51Sy27CMBC8+yui9I5SCBAOPVAgP4GiyLEXsHDsaG2jtl9fO48Wlx6q7iiXmc16duzjGRQglRVpKLueUTvFk5ckfVr0lZJGIwfsqWUWkJKLRvGhlaWyRichancKgfJaKC4YtXr4cV4UeblLCTlaeLMV6VC0FN97bV8GpMQA04pP7G4ekBILaMVEFsVicwitjjEwpuc2y4CUAOJ42MSQY+NOJ8CKUGaFVpH4Y9nnQ8A9XQenfo3O2WGFQ0DcIayEuqEYN3zn9bwNmKjagARmgUca03wIcD0v1uXehyvOF+m/4dh8ma9y71cJdlW0HVqzbFeUfWRh4LTaui8fmWjBWNp20cJWd4JFgTuU8eUkyZjYzADevGE/x9AzmMpLHE7USfuQsLVamdl4oQ+PKBsryu2ib2NAeREQiVFI+TbgV/1uyqqveztfb+nxVb8G/NPOKg/4q51P8RHUEFoDAAA=",
    },
    BundledTheme {
        name: "Macaw Light",
        payload_b64: "H4sIAAAAAAAA/4VSy27CMBC8+ysi944CKCEceoDE/gmEIsdZiIWxI9tBbb++dh6FlKJmlENm1ruzEx/OoMAweUQV45ez0Z2qo/cIv9GlxxqjSpsaTE/tkwCMGm3El1aOydJ0Enot3+d5scGoUwZYXQpVC86cHg7G8WZHKUbo4ODDHVFrxJWZz1ELD0YWuFb1xKZ5SjM/yoFxYiKzbL0lvo3tOAdre26bBGAExozDJgYdqu50AnNEjDuh1Uz8vSyhNBi802Vw6tdoOzdUxAHzCuEklBUz84J7XrsiYKJKCxK4g3qmcV0PAW5W2YZ6ohHnRvp3GFskJKYEIyX4RbHrUJrEaRHcDg2n1fZJntMQmbiCdezazhZ2uhV8FnhnZP+9JGkazqEoGhNbWDA3b9j3sewM9uilGk6sk+4pYee0sovxhz5dojiepj3k1ujbGBBZBczEWUh9Rrs/9Ycu+TLg0c7PXXoyRIqAF3Z6jby2Q/KA/+yQbQBG31URM7laAwAA",
    },
    BundledTheme {
        name: "Matrix",
        payload_b64: "H4sIAAAAAAAA/6VSy26DMBC88xUovUeNkLj1hMRPRAgZewErxkbrdZT262uXpxNyKhKXmfXszNjXDjQgU1XSMH7r0Dgt0q/09PH5952SxqAAnKGyDFBvUP4YTUzV6BTMXJYFzmkEJmqpheSMTHwwuRI8qEpGlAPD74izwI0WG1oUASVAkguY52WZ537UcQ7WRscBcV5WlpOT5Nq4tgWsEsZJGh2Nvwu7wnVw6mOMjqJ8+wlJCuqGLRkvl5e+9hXWFhRwAhFl4UZABPSy65X/47Va8ptmwzSaZSFjqCwIbtGmUZIDWGLDGBdpRskjxKFa1YrC95Wmc2NnC3j3hr2OZR3YylMCWuYUPV1n44iMtuf5Qt8/oq213tzhqbGNjCo6qHzhD1Q2M+tLOrDzsnEvNPXyXzuTyi/NecpMWAMAAA==",
    },
    BundledTheme {
        name: "midnight",
        payload_b64: "H4sIAAAAAAAA/4WSza7bIBCF9zxFRPdXxv9edEEMfomryCJ4kqDrQAT4qu3TFwc7t25SdeHNmfHMOd/wfgYNVowHdBTy42zNpIfd9x3+ljCyTylGR2MHsHcpJwWtKowuxqpfRnsx9nYa4V4LzWW2x2jSFsTQKz0oKbyJPyYJpV2HEXr38MMf0M2qq7A/7zWecMIYRg6k0cOqVlXNaIORB+vVKtKgsTa0TlKCc9ETDyrHCKxdlvEya/JyXnacTiewBySkV0Zv2v8Ku7r/kvvZaYhxm3yMQEmTdtsO5UfojyKuJSRN8+Qlryj1DkaQHuLGktCiTTGSZogA25qVvAhw1fkyhi+uzVhB6zBVK/mhxRUWnPuc1TOyeeAaLaU5K2dk6grOi+vtrtasaWgI7M1NyQ3ayY7RZd1Sngdeu91C7M2B/QyGwxwnzuAOoTTASUxjNNV1jJQLYe+Ndm/LQZ8e0QuuF/O54CFFmmb1prhB9CD6XP9jynqYLzOPl/Rk53GQV3aKtKJN8287ZduQffc/OzWnnGUY/QZH5fbIWAMAAA==",
    },
    BundledTheme {
        name: "Noctis Lilac",
        payload_b64: "H4sIAAAAAAAA/5WSz47CIBDG7zxF070brG1pD3uwf3gJYxqkoxIrGKBmd59+aWnduGo2S8JlZpjvm9+wOYAEzbot2jF+OmjVyzZ4D8K3uqpLmoVop3QLegzl5RoXOERHpcWXkpZ1je47GHNlWeFqHaJeamBtI2QrOLPKP8yyVV7TEKGNhQ+7RRctzkx/jjlcYpwWITLAlWznKEnIMqtDZEFbMQeTLI6oa2N6zsEY/xwXq9TZBK0nMUqTFR7Fdv1+D3qLGLdCSZ+s0xg7tV/D0ogux2Fv4WZw6sa49PZlhbAdNDvmZeuoojS941Uk66ou5lBjoANuwSsSnOIhx1XrAZIoI7RycMXh2LnrZaukHMlJwU+SnWGekOTRgGxoOI9WxIMaIQ6aOIOx7HzxW8vzpBii6iL4HdxedxPDMq3dXlEQTMwWBvTVWXZ9DDuA2bpUC3vWdxONOCdR4hlbq6RZTCt9+EZ4Onfkjuo6IfIYougu/QRUmj6teOg01P2Yuv2p/9paJ3lO6cDylS1f8ZcpX1W5tX4D2hiu+WgDAAA=",
    },
    BundledTheme {
        name: "Nord",
        payload_b64: "H4sIAAAAAAAA/32SzXLCIBCA7zyFQ++OCTHSQw/5wZdwnAwha2RMwAHitH36Yv5qqtMDl13Y/fZbDjUoMLw5opKLS210p6rVxwq/hYxE0QajUpsKTB+Ksm0cJxidtZHfWjneFKZroM+RNAq3IUadMsCrQqpKCu708JAGSZAFGKGDg093RFcjW26++lxOc8beMbIgtKqmaBzEjFKMHBgn56sbutt5JNsJAdb2sYSkjGYYgTFjs3TvHyf3ZmV3OoE5Ii6c1GpIRpQlOf477ET/Gy7upH6Ma+eWOh5uSNdAUfKhbUhCSoKXvoZQYaEB4aBaKBG6GgTSfZqlqZcr63Pjz9A2Ir4Iw0hJcVG8Ha/SbJPfPfQFp9Gmbk62YB1vr0uR+irFQnhnmkU1tFqNxtYWzM0D+zqW12CPPlXBiXfNAMU8KU0Hw85pZdfjQp8+0QuvZ30b9RBC8mixi6Wi2ehz/qFKwMIwTB5h5p/0hDMv5BXONom3u39wpo39jzPZ/AEizS4AWAMAAA==",
    },
    BundledTheme {
        name: "Nostromo Terminal",
        payload_b64: "H4sIAAAAAAAA/4VSy26DMBC8+ysQvUckIbQcemiQ/BMRQsbeECvGRn5Ebb++xjwqq0QdxIGZ9e542EsHEjQRNWoJvXdaOcmS9yR9yQJS1CrNQAfqFJCim9L8W0lLRKOdgKC9BaTISQ2ENVwyTolV00GMq2rshS4WPm2NBs17or/mORiPmgGqJFtYHJAiC9ryhTwH+FJHKRizHi+KFIHW67DcYxzWuusVdI0ItVzJyMmzy650Mzr11xicDRX7j/GJK7gV0LRkGrsP2MxrohoDAqgFFmlUsSnAosC4LH24vLsJ/9rImOT0LkkPUThTw+VqS6nlPRhL+iGwZYBn1cBplKLTInzneVWN3VCSzIntDOiHN+z7GNKBqb3E4EqcWEwdz3g/JWytkmY3/9CNJTqe9ocotZt6zPFkWVkcq0iMIsqyPD8cNvWoy7QAv2bWTfpjJ8+n1di0UwQ8t/Ma8J+dJe8fHSHZi1gDAAA=",
    },
    BundledTheme {
        name: "One Dark",
        payload_b64: "H4sIAAAAAAAA/7VSy26DMBC8+ysQvUcEbB6HHggJPxFFyDEbsAI2sk3U9uvr8GhipT3WFpfZYWdnvMcGBCjandCZsmuj5Chq793z38IgxGHuo7NUNagJSqL79VErFf+SwtCuUmMHUy0O4ihOfTQKBbSuuKg5o0bOP5ZlWgSBj9DRwIc5oUHxnqrPqbabjo80MCnqFU2T9JBZ1IAyfAVLjBOcWOrIGGg9E7MiT6wuKLWIFQnBZBI7j5cLqBOizHAppuKekHJ/8F/MpmER4We4uk9qbQyjmRjRNkrw1mVw00F1psolPPKKdjjA6QpVGjpgBmonLyZrcBy3vGk7+82yOCQksajg7CpoD47nueFq7a5FMhsZ70Eb2g/rm2WpdWbkwJkjNKpunmSbl4fS5uV5S2IbDepmB7Z9NG1An2yphgsduyULkoUFnhM2Rgq9WR70ZYmC5Ti5tfK2BkSiHMdO0QkJY7wj+a/1py4r6zHOzy79vdX/P843i8uNNVoDAAA=",
    },
    BundledTheme {
        name: "oslo",
        payload_b64: "H4sIAAAAAAAA/5VSy46jMBC8+ysi9j6yeSU+7IEA+YkoQo7pJFaIHdnNaHe/fo2JN2E1M9KAOFBdrq4u9/4MGqwYDuQo5PVszaj71c9V8oO2rE7rhByN7cEGKKV5u24TcjFW/TEaxdDZcYBQY3lWFuuEjNqC6DuleyUFmvlgQdfbrdcie4RfeCB3q27C/g61mtdNkyfEgTS6j+i64pu6SgiCRRVBvqt2NffUUUpwLmCbqmITEax9NIsI2R/H0wnsgQiJyuhQrPi2mIr/D1tQTnevcDc59WPcR5wZDeNpsWQoHKA7irkto2mZNYu8KJveCHUOBpAIc8eSbsra60nTzwG2m5a33tlFnS+D/zCq8txLaCWvWtxmKi8rHnIIgnE0lmVp7mdAdQOH4nYPaMbKlPs7Q3NXchHBaIfwvwuPz2u1eiT25sC+e8Nex4kzuIMv9XAS44ALhSlhRKPd2+NCP1+iZ2oX8x7jqVnBlqEvIqKlZ2Qf1l9VHiE/zfzbpO/ZiRv8mZ24/V/bydqyqTzrL5D+8xlYAwAA",
    },
    BundledTheme {
        name: "Oxocarbon",
        payload_b64: "H4sIAAAAAAAA/31STY+CMBS891eY7t1I+VAOe5AF/oQxpJanNkJL2mJ299dvS9HYqMuEAzPlvXnzujuBAEW7PTpQdjkpOYp28bnAH1HmgNFBqhbURJHMAaOzVPxXCkO7Ro0dBNooFNC24aLljBrpfyyqPK1rjNDOwLfZo0HxnqqfSatJndQbjDQwKdobmxIHjAwow2/krYweGQOtJy4hRZWlGIFSc7OqSuM8c80O4/EIao8oM1yKSYzLsihz/HbYO904p3aMYTT+RB1VURWe4KaD5kB92+jL4WVenmo0dMAM+I5ZnK42EUZMthAMd+anc2df3zZZxVliWcHZRdAegpl9wftoK5LHWxsZ70Eb2g+ezR0sKwfOgmhH1U3f6802n5azWMyJLTWoqzVs62h6Ar23UgtHOnbeVF2vq2JO2Bgp9HJe6NMlWs1PkNtZXueAotIhEIOQyNrhpf5QJc4cHu3c79KTIZI4vLFDNg7v7dyW8b+dNErizJr+A/sD1T1aAwAA",
    },
    BundledTheme {
        name: "plum",
        payload_b64: "H4sIAAAAAAAA/4VS247bIBR891dY7vsqXGzshz74xk+sIovgk4SuAxHgVduvLzF2FXe3WpAfPANn5gzn9QIarJiOyUnIt4s1sx7T72n2DWGEUJ8lJ2NHsBHqEMcsS67Gqt9GezENdp5g4SilLK+zZNYWxDgoPSopvIkXC8xwTbMkefXw0x+Tu1U3YX8tHC/DxlniQBo9bijDjJVB3YP1agObriI8aLhZSnBuwfIDr1mTJWDtKsZ5HtZD7DSfz2CPiZBeGb2STVm02b/NBn+MdD1+JoaH19DIffax+xo1mO5PKD/BcBJRmLSkzttdYod1beDgYALpYdx5l2aE1R2r2iIErC7XKXxRGDe4J6FtreSbFrf90Vhwa4/kpKLhhby6gfPidl/QNm9Q3tahhDd3JeOTdJzxkNJsp+W/bPqKdyG1NF1ze3Fg34PlUMmJC7hjoH4YFYUwfewmxJGmI5zFPEWvHPG6bGP43hvtXta3/jBflJKqKHZxXs37mhsucU325C45RgtcHT7ln6oQRBBFz2b+DtkHO1vIn9ohmBSU/t8OaQLff2UnL2jNwoj9AS20zHRzAwAA",
    },
    BundledTheme {
        name: "portland",
        payload_b64: "H4sIAAAAAAAA/5WSy26DMBBF9/4K5O6j0DxoF10kTfmJCCFjJokVYyM/orZfX4/BTaiaSp0jFtwxM+PL7I+gwDBZkYbx89For9rsJaMPj0uEkkabFkyUVgVCyUkb8amVY7I2XkLMLXOEEq8MsLYWqhWcOT18WMSghOwdvLuK9EZ0zHzE3G6OUGKBa9Um9alEKHFgnEjiZoeEo55zsDZqz1uEEjBmbJYUsm/84QCmIow7oVVMblcI/XnZOMPuVq5x0nCN3rvBjjkyPSGchLphQ9tFjkz8msdIUm1BAncwdCxKhBKu28HAtw0SzBXHkwzP0HYRgxIl+Fmxbji6WSFoGRZMV1u8IsEy0YF1rOujui6QoOpe8IkF3sj4XsYIfmXZ6NjMgrmEgUMdy45gq5Bq4cC8dJMK6LBzWtnZ+EPvL9HVtZO+jPbkW2SSnFiUx/g1f1MlmXwd5nuT/jdO2uB746Tt/3ucdYlQ8gUGdNkSWAMAAA==",
    },
    BundledTheme {
        name: "Rose Pine",
        payload_b64: "H4sIAAAAAAAA/32Sz27CMAzG73mKqrujtpQChx3ov5dAqEpTUyLapEoctO3pF2jDVgaLlMtnx/78c/YtCFC0O5CasnOrpBGN9+75b1EYBVHhk1qqBtRNioNlvop8cpKKf0mBtKuU6WBMT6LlcucTIxTQpuKi4YyiHB+WSRau1z4he4QPPJBB8Z6qz1usSNMstQ81MCkap26DTbazKoJC7sQs3q0LW0YbxkDrMTHLynzjE1BqalakSbmNrs1qczyCOhDKkEsxS3817F2urk7tGIPBW0a4DddRPM/g2EFV07FtWIb5A69gOk6sNHTAEMaeSZHsNolPmGxgZvzE21NnL86gC87OgvbwAO1a0A3ndoC8B420H27qKorLxFJDOXA2g2tUN1YL8qK0sxHPm5gtNKiLNWzraNqCPthQA0dqOnxYaG0QpdCLaaWvv9EPt5O8TICeBGeInkB38V9VHPkfM/e/9NfOhOipHYf6lR1H8n87bq/f6u6/D1oDAAA=",
    },
    BundledTheme {
        name: "Rose Pine Dawn",
        payload_b64: "H4sIAAAAAAAA/32SwXKCMBCG73kKJr07VkTMoQcq8BIOw4SwYkZMnGTjtH36RiFaWi0zufy77P/n22w7UGB4X5GGi0NntFNt9BbRl3JZ5MWakkabFsxVyss8yxkle23kl1bI+9q4Hob2RcGKV0qcMsDbWqpWCo56+LHIWB4vKSFbhA+syMnIIzefw9B0vUgLSiwIrdqgpixNWEwJgkEZRDZPs8z7WycEWHvVkhVbspISMGY0e1+u4jS7mDVutwNTES5QajVpf3bZm1xfkvprnBwOHdmlZ9ohsYe64YNtWfqWeMJrPn5BrC30IBAGT7ZmcZZQInQLk+B72e17f3ACXUlxUPwIv6BdBobLhR2gPIJFfjxd1U2xyTY+OeqTFBO4zvQDlDRZpN6CRNHIbGbBnH1gP8fyDmzlSy3suOvx10Ibh6iVnY0rff6M7tz2+jwCelCcIHoAPdR/ThnJ38Pc3tLfOCOih3EC6mdxAsn/44S9fgMZhwOjWgMAAA==",
    },
    BundledTheme {
        name: "Rose Pine Moon",
        payload_b64: "H4sIAAAAAAAA/32S3W6CQBCF7/cpDL03yp9y0QuK8BLGkGUZcSPumtlZ0/bpu4KrwdaScHPOMHPmG7YdKEDe71jDxbFDbVU7e58Fb2EerqMyYI3GFnCQ4jheJnnADhrlt1bE+xptD4MXZVGShAGzCoG3tVStFJz0+GGVFsvVKmBsS/BJO3ZGeeL4NXhlnuWZ8wwIrVqvZot1kbtRBEjSi0Wcr8prqRUCjBkLi6LarAMGiLdh5UdaZeF1WGP3e8Ad44KkVpPyV8ve5fqa1K1xtjRWROEySqcVknqoG46+xSqqJrwWt8eLtYEeBME4My3TfO06Ct3CJPhBdofevTSBrqQ4Kn6CJ2jXhn45fwOSJzDET+dBTdIkTN1upM9STOBa7Mdui01ZxY7YbHZjNjeAFxfY9TG8A7NzVgt7bnt6OmhjibQy89tJX/9GD24HfQF8ZU4Q/QHd+9MuA/lHmPu/9CuOR/RnHI/6VRxP8v84/q4/fWpSoVoDAAA=",
    },
    BundledTheme {
        name: "Solarized Dark",
        payload_b64: "H4sIAAAAAAAA/8VSy26DMBC88xWI3iMeCYFDD5C0PxEhZOwNWDE2WttR26+vCaGRpabXHrjM7M7ODD71IAGJaIKO0EuPykoWvobRSxyndZZHQaeQAd6gMquSKomCQSH/UtIQ0aIV4HFWIhDWcsk4JUb5i8HJwIdpggn5SPDzxhVZuS3dHQ1USbaiuyJ/2++iwAAavoKrjLaUgtbL+q4s4zgKAPF+7HjI0vR9PtbZ8xmwCQg1XMkbeai3dTKnehL2B25npy7GZM0ysc/ybepPcCOg7Qj6A4++1mgL1GoQQA0wLwtVbCnwmGV54fYH3g/Cff5ZyelFknEZTfOiPqZzZbPgGm3NYPgI2pBx8otUE6eeK4tiUauqpCxcX2F4b2yjAa/OsNPRpAfdOIrBmVhhPM25YWOU1Jv7D33+iB6tDeoK+KxSr6I/+F9UHmZ+XtJ/2vkGohJX5FgDAAA=",
    },
    BundledTheme {
        name: "Sonokai",
        payload_b64: "H4sIAAAAAAAA/31SSW6DMBTd+xSI7qPUZlx0E4ZLRAgZ8wNWwEa2idqevg5DBE1aWWzeN2/yPzcgQNGuQBVl10bJUdTOh+O+4QRnxHNRJVUNaoK8d8/3jy5qpeLfUhjalWrsYJqRE8m8yEWjUEDrkouaM2rk/GMWJkFgudDZwKcp0KB4T9XXPMP2EBdpYFLUKxrmkRdbKQPK8BXMSRwEFtQjY6D1hMVZegyxi0CpRSxP/DRM7mLVeLmAKhBlhksxDU8kTnOr9issIcQn+RYu705tjGE0+zo2N7jpoKzoLIsxJjjc9bV2MkOlhg6YgVkxDJIks1mYrGEXruVN29lvliUBiT0rKzi7CtrD7t+ZcI22XjW8B21oP0yoH/t5YJMZOXC2q3ZU3Y4NOc7S2EGDulnDlkfTBnRhRzVc6NiZHcO9YWOk0IflQZ+W6EWvrbwt9byodFfRo9Hn+YblPbIn3pp5bNKTnXWBX9p5vNYfdtae/rcT+SnJ7T7+AJC3eRxYAwAA",
    },
    BundledTheme {
        name: "sunset",
        payload_b64: "H4sIAAAAAAAA/4WS3Y6CMBCF7/sUhL03IoJwsRcV5CUMIaWM0Agt6Y/Z3affCiKyahbCzZly5sw3PdbAQZI2RyWh51oKwyvn03E/POzhzcFFpZAVyEHKsjjzEhc1QrIfwTVpC2laGGob+/h7FxkugVQF4xWjRIvpx3Af2iI6avjSOeol64j8HmvB9XWRAip4dVczHMa2uwap2SyO/ZWhFJQatO0hSZOti0DKp2alOZ1A5ohQzQRfWPwZdko/y8U1qR2jN3qJ4+EE0y0UJRnb+tjHQfKS1ygVClqgGsaO2W4TRHZsKipYxG5Y3bT2G9smu/Xaj13EGT1z0sGSw2A4jRZgL4qxRcY6UJp0/Xg2OsTYs6roGV2gNbJdEESOcyO2UiAvNrD1UaQGldtSBSdiWr3wvBLWWnC1ui30/SWaqTXicsPzAvoC0Z3oc/3BZRp7DnO/SU9xnrf/YDQt4F2cLNumYfpfnDTyvMAu7Bf8Bj0EWAMAAA==",
    },
    BundledTheme {
        name: "tofino",
        payload_b64: "H4sIAAAAAAAA/4WSzW7jIBSF9zxF5NlXxmADi1n49yWqyCL4JkF1IAJczczTF8d227SNZuEF917fc84Hzycw4OS4RwepXk7OTmbY/d4lv3COO5Il6GDdAO5WyjhpC5ags3X6nzVBjr2bRljG66yiPEGTcSCHXptBKxns8iPFnNA8Qeg5wJ+wR1enL9L9vfUEKWnTJsiDsmbYqpQUpIzqAVzQWzFnjFVlHJ2UAu+XWseaGicInFvF8lSQPJ3FDtPxCG6PpAramluT80qw2PwSNu1i3OpzuZ+dxhjXKSz5Mlxm/H5ChxH6g1xkcZM1tLzjlTZxK9tKvYcRVIBFkbSsozGgssMCsCZ10ZEIV5/OY/xW2ZIUuE6Q0erFyMsyWoq64nhGNi/couEqEzQuCPoCPsjLddXJWxFtBXvVakGQCtbEy5jceDs3bSO6LvLa7VZiTx7cazQc93h5Ar+PrQGOchrDHcSZcAjW+Kf1Qh8/og9qZ/u64vkB6R0inOICtz/2P23ZIH+YeX9J3+0UWUroAzskpSWrHtshPM958z87VBSijLzfAIZVeplYAwAA",
    },
    BundledTheme {
        name: "Tokyo Night Storm",
        payload_b64: "H4sIAAAAAAAA/5WSy27CMBRE9/4K5O4RcV5k0YUTkp9AKDLOJbEwNrId1PbrmxctAdqqi2xmnDtzj72tQYFhcof2jB9ro1tVLV4X+MWjXkoijPbaVGAGiSQkDwhGjTbiQyvHZGlaCYMXU0qKGKNWGWBVKVQlOHN6/DHeZEVRYIS2Dt7cDp2NODHzPnjZKqNFiJEFrlV1VWmSepsu3YFx4uFoyzlYO9VMsyTDCIyZwoo4jtZ5H7ZvDwcwO8S4E1oNZpomtK95tywJyNpPb+Wyb9qtcW7djyeEk1Du2RjrFcT3w6e8Rqm0IIE7GBOTPMsjihHXFcw2bkTdyO4bY/MVLaI1Rkrwo2InuBG9pIfWj7wuFwZhFud+l+jECaxjp/Mcpj4LPr8tI2cU0WIxUVtaMJeudDfHshrsrrMqOLBWutmEnrJzWtnldKkPD2lsNSPX6Ms9om9zhslPAxJ5T/2bKY9lvl7T/+r8Ejf4gUejNPyrzpXmJw4iCxlcAwAA",
    },
    BundledTheme {
        name: "vanimo",
        payload_b64: "H4sIAAAAAAAA/4WSzY7bIBSF9zxF5O5HxoCNF10Y/7zEKLIIvknQOBABHrV9+uK/zqSdqAtvzrlwzv3M6wUMODke0Umqt4uzkxkO3w/Jt6zCLKMJOlk3gFsk1maM4QRdrdO/rAly7N00wuKRFleEJWgyDuTQazNoJYPdDoqizUSC0GuAH+GI7k7fpPu5eA3huI45HpQ1w66WJSU8T1AAF/QuVg0jZRVHJ6XA+0UTGeNllyBwbgvLGa8JnsNO0/kM7oikCtqaxeRMMNokfy+LG0xx8Vnu56ZxjfsUVhw0TrSPEzqM0J/kGktTLEjxwAuLeIbtUu9hBBVgTWRlIbK4i7LDCrBLRdryCFdfrmP8tlhGUhzpGK3ejLyto2XVpDmfkc0X7quREpfz3kHfwAd5u6+zGWl5GlV712pRal5gEYtOblyDu7rpIhJ0OGzEXjy491g43uPlBfwxWgOc5TSGB4gz4RCs8S/bD33+iD6oXe37hucLpA+IcBt9/qX/6ZYd8keZPy/p3zo1zjP2pE5Bszanz+vwnBQF+1+dsqOc1wn6DWF2jcdYAwAA",
    },
    BundledTheme {
        name: "VESPER",
        payload_b64: "H4sIAAAAAAAA/31STW/CMAy951dU2R11dBP0sAOC9U+gqkoTUyLSpHIStO3Xr+kHEBjzUy/Prv384n0DGpCpktSMnxo0XovkI6Evr2kAJbVBAThQ2RCUHA3KH6MdUxV6BUNuuQ6gxGsEJiqpheTMmfHHotiu8pwSsnfw5UrSoWwZfk+5EJRY4EaLmd2kAZQ4QCdncpUF9KWec7B24PK8KD7fKAHEy7B1uk7DsNofDoAlYdxJo6Pyu2XTXcAtXQWl/Rqdd2PFoCiukE5BVTOMC65+pVPMZGVBAXcgIlO4ERARR9kcVf+Ng5dZACVa8pNmbVw6NpyXW24CetNkC9axthvY9yygZ00neWSuRxWZQpJk8mxhAc+94L6PZQ3Ysk8JODCv3N2D1t45o+1ietLnZ3T17WjOk0Gv24AoGVk07/5H/qbLvPZVzOWWHuU8TrxpNN3wMznz/f8vJ9sFUPILKkBis1oDAAA=",
    },
    BundledTheme {
        name: "vik",
        payload_b64: "H4sIAAAAAAAA/4WSy27bMBBF9/wKg90HfMh6LLqgHv6JwBBoamwTkUmDpIK2X19KlBqnTdKFFry8mrlzhs8XMODkeEQnqV4uzk5m2H3f4W+ckAMhGJ2sG8At0p7RkmQYXa3Tv6wJcuzdNEKyd5QRitFkHMih12bQSgabfmRdkVcVRug5wI9wRHenb9L9XO6arNjnAiMPypphU0vGC8YwCuCC3sQqzwTPo3VSCrxPWpMdeIsROLc243m5F+3c7DSdz+COSKqgrUkj1CJra/z3sIySmvBHuZ+TxjHuU0gOQbp5vkeHDiP0J5naZjQBeOBFm1g136TewwgqwNqxKXgVWSo7JICdqKpqH+Hqy3WMX2pLGWt4iZHR6sXIW7IWuai7ZkY2F9xG4zWl88KCvoEP8nZP3pZntIuqvWu1KHU+A4qbcuNyPhxEu/Da7VZiTx7cawwc63h5AX+MVwOc5TSGdxBnwiFY45/WhX7+iN6oXe3riucDpO8RcdIQ9uH9Q5UN8luYPy/p3zj0izh53B+pP49TECZo9r84ZclbFhf2G+nNbQ9YAwAA",
    },
    BundledTheme {
        name: "Zenburn",
        payload_b64: "H4sIAAAAAAAA/5VSy26DMBC8+ysQvUekDQkceiCAfyKKkDEbsELsyI+o7dfXBlNK0lYqKw6eHe/OzvrQAgdJ+iOqCT23UhjeBK9B+PSSuAhRLWQDcoCysthGUYg6IdmH4Jr0lTQ9DLnN1kWIDJdAmorxhlGixXgxLjMbIUIHDW/6iK6SXYh8H3JFXuR5HiIFVPBmQtM4jZMsRBqkZhOIowJn2FINpaDUWBonO6cJpPTNil2MHYIOtTmdQB4RoZoJPpbA+2Rru90Pi118hyun1I5xNXpkrF0sGUz3UNVELgmzX5H/JrBS0APV0CzcpKIBr22X5tbCjrVdb3/fuNjgjZXGGT1zcvHUNC3SxJnmCk7Dbddx7qiaXUBpcrl61OEWFVdGBySP8vXe8ozsh3OyL1NcWMeCwHu2UiBvVrCto0gL6mhTDZyI6fXdQmujteBq5Vf6+zOafevEzRv0XLpYJBcW/XB5yv9QZRbz9ZYe5Twuei70R7t/yJlYn5i/JgZaAwAA",
    },
];

/// Decompress every bundled theme into `(name, toml_text)` pairs.
/// Intended for the one-time `ThemeManager::init_themes_dir`
/// extraction. Do not call in hot paths — each call decodes
/// ~50 KiB of gzip data.
pub fn bundled_themes_decoded() -> SnipResult<std::vec::Vec<(String, String)>> {
    BUNDLED
        .iter()
        .map(|b| {
            let compressed = base64::engine::general_purpose::STANDARD
                .decode(b.payload_b64)
                .map_err(|_| {
                    crate::SnipError::runtime_error("bundled theme: invalid base64", None)
                })?;
            let mut toml_bytes = std::vec::Vec::new();
            flate2::read::GzDecoder::new(compressed.as_slice())
                .read_to_end(&mut toml_bytes)
                .map_err(|_| {
                    crate::SnipError::runtime_error("bundled theme: invalid gzip stream", None)
                })?;
            let toml_text = String::from_utf8(toml_bytes).map_err(|_| {
                crate::SnipError::runtime_error("bundled theme: non-utf-8 toml", None)
            })?;
            Ok::<(String, String), crate::SnipError>((b.name.to_string(), toml_text))
        })
        .collect::<Result<Vec<(String, String)>, crate::SnipError>>()
}
