use crate::error::SnipResult;

/// Supported shell types for integration generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellType {
    Bash,
    Zsh,
    Fish,
}

impl std::fmt::Display for ShellType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ShellType::Bash => write!(f, "bash"),
            ShellType::Zsh => write!(f, "zsh"),
            ShellType::Fish => write!(f, "fish"),
        }
    }
}

/// Generate and print shell integration code for the specified shell.
pub fn run(shell: ShellType) -> SnipResult<()> {
    let code = match shell {
        ShellType::Bash => generate_bash(),
        ShellType::Zsh => generate_zsh(),
        ShellType::Fish => generate_fish(),
    };
    print!("{code}");
    Ok(())
}

/// Selection adapters use a temp file, while creation adapters pass command
/// text over stdin without shell evaluation.
fn generate_bash() -> String {
    r#"# Bash integration for snp — Generated by `snp shell init bash`
# Adds selection, current-buffer capture, and previous-history functions.
# No keybindings are installed by default. Bind manually if desired.
# Inspect this output before sourcing.

__snp_select() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi

  local mode="$1"
  local old_line="$READLINE_LINE"
  local old_point="$READLINE_POINT"

  local tmp_file
  tmp_file="$(mktemp "${TMPDIR:-/tmp}/snp-select.XXXXXX")"

  local args=(--output-file "$tmp_file" --"$mode")
  if [[ -n "$READLINE_LINE" ]]; then
    args+=(--query "$READLINE_LINE")
  fi

  snp select "${args[@]}"
  local rc=$?

  if [[ $rc -eq 4 ]]; then
    rm -f "$tmp_file"
    READLINE_LINE="$old_line"
    READLINE_POINT="$old_point"
    return 0
  fi

  if [[ $rc -ne 0 ]]; then
    rm -f "$tmp_file"
    READLINE_LINE="$old_line"
    READLINE_POINT="$old_point"
    return "$rc"
  fi

  if [[ ! -f "$tmp_file" ]]; then
    echo "snp: selection output was not produced" >&2
    rm -f "$tmp_file"
    READLINE_LINE="$old_line"
    READLINE_POINT="$old_point"
    return 1
  fi

  local selected
  IFS= read -r -d '' selected < "$tmp_file"
  rm -f "$tmp_file"

  READLINE_LINE="$selected"
  READLINE_POINT="${#selected}"
}

snp_select_raw() {
  __snp_select raw
}

snp_select_expanded() {
  __snp_select expanded
}

snp_new_current() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi
  if [[ -z "${READLINE_LINE+x}" ]]; then
    echo "snp: Bash Readline buffer API is unavailable (Bash 4+ required)" >&2
    return 1
  fi

  local old_line="${READLINE_LINE-}"
  local old_point="${READLINE_POINT-}"
  printf '%s' "$old_line" | command snp new --command-stdin "$@"
  local -a pipe_status=("${PIPESTATUS[@]}")
  READLINE_LINE="$old_line"
  READLINE_POINT="$old_point"
  return "${pipe_status[1]:-1}"
}

snp_new_previous() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi

  # A normal function call is itself a history event; a bind -x widget is
  # not. Select the previous event in the former case and the latest event
  # in the latter case, before invoking any external command.
  local event=-2
  if [[ -n "${READLINE_LINE+x}" ]]; then
    event=-1
  fi

  local tmp_file
  tmp_file="$(mktemp "${TMPDIR:-/tmp}/snp-history.XXXXXX")" || return 1
  if ! fc -ln "$event" "$event" >"$tmp_file" 2>/dev/null || [[ ! -s "$tmp_file" ]]; then
    rm -f "$tmp_file"
    echo "snp: previous shell history is unavailable" >&2
    return 1
  fi

  # Bash's `fc -ln` formatter prefixes the first line with tab+space. Remove
  # only that formatter prefix so leading spaces in the command remain data.
  tail -c +3 "$tmp_file" | command snp new --command-stdin "$@"
  local -a pipe_status=("${PIPESTATUS[@]}")
  rm -f "$tmp_file"
  return "${pipe_status[1]:-1}"
}

# To bind manually, add to your .bashrc:
#   bind -x '"\C-o": snp_select_raw'
#   bind -x '"\C-o\C-e": snp_select_expanded'
#   bind -x '"\C-n": snp_new_current'
#   bind -x '"\C-p": snp_new_previous'
"#
    .to_string()
}

fn generate_zsh() -> String {
    r#"# Zsh integration for snp — Generated by `snp shell init zsh`
# Adds selection, current-buffer, and previous-history ZLE widgets.
# No keybindings are installed by default. Bind manually with:
#   bindkey '^O' snp_select_raw
# Inspect this output before sourcing.

__snp_select() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi

  local mode="$1"
  local old_buffer="$BUFFER"
  local old_cursor="$CURSOR"

  local tmp_file
  tmp_file="$(mktemp "${TMPDIR:-/tmp}/snp-select.XXXXXX")"

  local -a args=(--output-file "$tmp_file" --"$mode")
  if [[ -n "$BUFFER" ]]; then
    args+=(--query "$BUFFER")
  fi

  snp select "${args[@]}"
  local rc=$?

  if [[ $rc -eq 4 ]]; then
    rm -f "$tmp_file"
    BUFFER="$old_buffer"
    CURSOR="$old_cursor"
    zle redisplay
    return
  fi

  if [[ $rc -ne 0 ]]; then
    rm -f "$tmp_file"
    BUFFER="$old_buffer"
    CURSOR="$old_cursor"
    zle redisplay
    return $rc
  fi

  if [[ ! -f "$tmp_file" ]]; then
    echo "snp: selection output was not produced" >&2
    rm -f "$tmp_file"
    BUFFER="$old_buffer"
    CURSOR="$old_cursor"
    zle redisplay
    return 1
  fi

  local selected
  IFS= read -r -d '' selected < "$tmp_file"
  rm -f "$tmp_file"

  BUFFER="$selected"
  CURSOR="${#BUFFER}"
  zle redisplay
}

zle -N snp_select_raw () { __snp_select raw }
zle -N snp_select_expanded () { __snp_select expanded }

__snp_new_current() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi

  local old_buffer="$BUFFER"
  local old_cursor="$CURSOR"
  printf '%s' "$old_buffer" | command snp new --command-stdin "$@"
  local -a pipe_status=("${pipestatus[@]}")
  BUFFER="$old_buffer"
  CURSOR="$old_cursor"
  if [[ -n "${WIDGET-}" ]]; then
    zle redisplay
  fi
  return "${pipe_status[2]:-1}"
}

snp_new_current() {
  __snp_new_current "$@"
}

__snp_new_previous() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi

  local old_buffer="$BUFFER"
  local old_cursor="$CURSOR"
  local event=-2
  if [[ -n "${BUFFER+x}" ]]; then
    event=-1
  fi

  local tmp_file
  tmp_file="$(mktemp "${TMPDIR:-/tmp}/snp-history.XXXXXX")" || return 1
  if ! fc -ln "$event" "$event" >|"$tmp_file" 2>/dev/null || [[ ! -s "$tmp_file" ]]; then
    rm -f "$tmp_file"
    echo "snp: previous shell history is unavailable" >&2
    return 1
  fi

  command snp new --command-stdin "$@" <"$tmp_file"
  local rc=$?
  rm -f "$tmp_file"
  BUFFER="$old_buffer"
  CURSOR="$old_cursor"
  if [[ -n "${WIDGET-}" ]]; then
    zle redisplay
  fi
  return "$rc"
}

snp_new_previous() {
  __snp_new_previous "$@"
}

# To bind, add to your .zshrc:
#   bindkey '^O' snp_select_raw
#   bindkey '^O^E' snp_select_expanded
#   bindkey '^N' snp_new_current
#   bindkey '^P' snp_new_previous
"#
    .to_string()
}

fn generate_fish() -> String {
    r#"# Fish integration for snp — Generated by `snp shell init fish`
# Adds selection, current-buffer, and previous-history functions.
# No keybindings are installed by default. Bind manually with:
#   bind \co snp_select_raw
# Inspect this output before sourcing.

function __snp_select --argument-names mode
  if not command -q snp
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  end

  set -l old_cmdline (commandline)
  set -l old_cursor (commandline -C)

  set -l tmp_file (mktemp "/tmp/snp-select.XXXXXX")

  set -l snp_args --output-file "$tmp_file" --"$mode"
  if test -n "$old_cmdline"
    set snp_args $snp_args --query "$old_cmdline"
  end

  snp select $snp_args
  set -l rc $status

  if test $rc -eq 4
    rm -f "$tmp_file"
    commandline -C "$old_cursor"
    commandline -r "$old_cmdline"
    return
  end

  if test $rc -ne 0
    rm -f "$tmp_file"
    commandline -C "$old_cursor"
    commandline -r "$old_cmdline"
    return $rc
  end

  if not test -f "$tmp_file"
    echo "snp: selection output was not produced" >&2
    rm -f "$tmp_file"
    commandline -C "$old_cursor"
    commandline -r "$old_cmdline"
    return 1
  end

  set -l selected (cat "$tmp_file" | string split0)
  rm -f "$tmp_file"

  commandline -r "$selected"
  commandline -C (string length -- "$selected")
end

function snp_select_raw
  __snp_select raw
end

function snp_select_expanded
  __snp_select expanded
end

# commandline writes one output line terminator; remove exactly that one after
# collecting the complete buffer so a buffer-supplied trailing newline remains.
function __snp_current_buffer
  commandline | string collect --no-trim-newlines | string replace -r '\n$' '' | string collect --no-trim-newlines
end

function snp_new_current
  if not command -q snp
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  end

  set -l old_cmdline (__snp_current_buffer)
  set -l old_cursor (commandline -C)
  set -l current $old_cmdline
  printf '%s' "$current" | command snp new --command-stdin $argv
  set -l pipe_status $pipestatus
  commandline -r "$old_cmdline"
  commandline -C "$old_cursor"
  return $pipe_status[2]
end

function snp_new_previous
  if not command -q snp
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  end

  # Fish exposes history entries through its builtin API. Request two entries
  # because a normal function invocation can be the newest history event;
  # widgets invoked before Enter see the latest accepted command as item one.
  set -l history_items (history search --max=2 --null | string split0)
  if test (count $history_items) -eq 0
    echo "snp: previous shell history is unavailable" >&2
    return 1
  end
  set -l previous $history_items[1]
  if string match -q -- 'snp_new_previous*' -- "$previous"
    if test (count $history_items) -lt 2
      echo "snp: previous shell history is unavailable" >&2
      return 1
    end
    set previous $history_items[2]
  end
  if test -z "$previous"
    echo "snp: previous shell history is unavailable" >&2
    return 1
  end

  printf '%s' "$previous" | command snp new --command-stdin $argv
  return $pipestatus[2]
end

# To bind, add to your config.fish:
#   bind \co snp_select_raw
#   bind \co\e snp_select_expanded
#   bind \cn snp_new_current
#   bind \cp snp_new_previous
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    #[test]
    fn test_shell_type_display() {
        assert_eq!(ShellType::Bash.to_string(), "bash");
        assert_eq!(ShellType::Zsh.to_string(), "zsh");
        assert_eq!(ShellType::Fish.to_string(), "fish");
    }

    #[test]
    fn test_bash_generation_contains_required_elements() {
        let code = generate_bash();
        assert!(code.contains("snp_select_raw"));
        assert!(code.contains("snp_select_expanded"));
        assert!(code.contains("__snp_select"));
        assert!(code.contains("READLINE_LINE"));
        assert!(code.contains("READLINE_POINT"));
        assert!(code.contains("--output-file"));
        assert!(code.contains("--query"));
        assert!(code.contains("snp select"));
        assert!(code.contains("snp_new_current"));
        assert!(code.contains("snp_new_previous"));
        assert!(code.contains("--command-stdin"));
        assert!(code.contains("fc -ln"));
        assert!(code.contains("mktemp"));
        assert!(code.contains("command -v snp"));
    }

    #[test]
    fn test_zsh_generation_contains_required_elements() {
        let code = generate_zsh();
        assert!(code.contains("snp_select_raw"));
        assert!(code.contains("snp_select_expanded"));
        assert!(code.contains("__snp_select"));
        assert!(code.contains("BUFFER"));
        assert!(code.contains("CURSOR"));
        assert!(code.contains("zle -N"));
        assert!(code.contains("zle redisplay"));
        assert!(code.contains("--output-file"));
        assert!(code.contains("--query"));
        assert!(code.contains("snp select"));
        assert!(code.contains("snp_new_current"));
        assert!(code.contains("snp_new_previous"));
        assert!(code.contains("--command-stdin"));
        assert!(code.contains("fc -ln"));
    }

    #[test]
    fn test_fish_generation_contains_required_elements() {
        let code = generate_fish();
        assert!(code.contains("snp_select_raw"));
        assert!(code.contains("snp_select_expanded"));
        assert!(code.contains("__snp_select"));
        assert!(code.contains("commandline"));
        assert!(code.contains("commandline -C"));
        assert!(code.contains("--output-file"));
        assert!(code.contains("--query"));
        assert!(code.contains("snp select"));
        assert!(code.contains("snp_new_current"));
        assert!(code.contains("snp_new_previous"));
        assert!(code.contains("--command-stdin"));
        assert!(code.contains("history search"));
    }

    #[test]
    fn test_no_eval_in_generated_code() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(!code.contains("eval "));
            assert!(!code.contains("eval\""));
            assert!(!code.contains("eval '"));
            assert!(!code.contains(".bash_history"));
            assert!(!code.contains(".zsh_history"));
            assert!(!code.contains("fish_history"));
        }
    }

    #[test]
    fn test_cancellation_preserves_buffer() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(code.contains("4"));
            assert!(code.contains("old_"));
        }
    }

    #[test]
    fn test_all_shells_check_for_snp() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(code.contains("snp"));
            assert!(code.contains("not found") || code.contains("not found"));
        }
    }

    // H1: Generated syntax tests — validate with shell parsers

    fn shell_exists(name: &str) -> bool {
        Command::new("which")
            .arg(name)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    #[test]
    fn test_bash_syntax_check() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }
        let code = generate_bash();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let output = Command::new("bash")
            .args(["-n", tmp.path().to_str().unwrap()])
            .output()
            .expect("failed to run bash -n");

        assert!(
            output.status.success(),
            "bash -n failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_zsh_syntax_check() {
        if !shell_exists("zsh") {
            eprintln!("skipping: zsh not found");
            return;
        }
        let code = generate_zsh();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let output = Command::new("zsh")
            .args(["-n", tmp.path().to_str().unwrap()])
            .output()
            .expect("failed to run zsh -n");

        assert!(
            output.status.success(),
            "zsh -n failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_fish_syntax_check() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }
        let code = generate_fish();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let output = Command::new("fish")
            .args(["--no-execute", tmp.path().to_str().unwrap()])
            .output()
            .expect("failed to run fish --no-execute");

        assert!(
            output.status.success(),
            "fish --no-execute failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    // H2: Function-definition tests — source and verify functions exist

    #[test]
    fn test_bash_functions_exist_after_source() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }
        let code = generate_bash();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let check = format!(
            ". {} && type snp_select_raw && type snp_select_expanded && type snp_new_current && type snp_new_previous",
            tmp.path().to_str().unwrap()
        );
        let output = Command::new("bash")
            .args(["-c", &check])
            .output()
            .expect("failed to run bash");

        assert!(
            output.status.success(),
            "bash function check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_zsh_functions_exist_after_source() {
        if !shell_exists("zsh") {
            eprintln!("skipping: zsh not found");
            return;
        }
        let code = generate_zsh();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let check = format!(
            "source {} && which snp_select_raw && which snp_select_expanded && which snp_new_current && which snp_new_previous",
            tmp.path().to_str().unwrap()
        );
        let output = Command::new("zsh")
            .args(["-c", &check])
            .output()
            .expect("failed to run zsh");

        assert!(
            output.status.success(),
            "zsh function check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_fish_functions_exist_after_source() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }
        let code = generate_fish();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let check = format!(
            "source {} && functions -q snp_select_raw && functions -q snp_select_expanded && functions -q snp_new_current && functions -q snp_new_previous",
            tmp.path().to_str().unwrap()
        );
        let output = Command::new("fish")
            .args(["-c", &check])
            .output()
            .expect("failed to run fish");

        assert!(
            output.status.success(),
            "fish function check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    // H5: Non-execution sentinel — verify widget doesn't execute

    #[test]
    fn test_bash_does_not_execute_on_source() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }
        let sentinel = tempfile::NamedTempFile::new().unwrap();
        let sentinel_path = sentinel.path().to_str().unwrap().to_string();
        drop(sentinel);

        let code = generate_bash();
        let script = format!(
            "{}\nsnp_select_raw() {{ echo '{}' > '{}'; }}",
            code, "SENTINEL_CREATED", sentinel_path
        );

        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &script).unwrap();

        // Source the file — functions are defined but not invoked
        let output = Command::new("bash")
            .args(["-c", &format!(". {}", tmp.path().to_str().unwrap())])
            .output()
            .expect("failed to run bash");

        assert!(
            output.status.success(),
            "bash source failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        // Verify sentinel was NOT created
        assert!(
            !std::path::Path::new(&sentinel_path).exists(),
            "sentinel file was created during source — non-execution violated"
        );
    }

    // H4: Special-character tests in function content

    #[test]
    fn test_bash_handles_quotes_in_generated_code() {
        let code = generate_bash();
        assert!(code.contains("\"snp\"") || code.contains("'snp'"));
    }

    #[test]
    fn test_zsh_handles_quotes_in_generated_code() {
        let code = generate_zsh();
        assert!(code.contains("\"snp\"") || code.contains("'snp'"));
    }

    #[test]
    fn test_fish_handles_quotes_in_generated_code() {
        let code = generate_fish();
        assert!(code.contains("\"snp\"") || code.contains("'snp'"));
    }

    // Test that output_file flag is handled for cancellation cleanup

    #[test]
    fn test_output_file_cleanup_on_cancellation() {
        let tmp = tempfile::NamedTempFile::new().unwrap();
        let path = tmp.path().to_path_buf();
        drop(tmp);

        std::fs::write(&path, "test").unwrap();
        assert!(path.exists());

        let _ = std::fs::remove_file(&path);
        assert!(!path.exists());
    }

    // Test that generated code uses --output-file, not stdout

    #[test]
    fn test_all_shells_use_output_file() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(
                code.contains("--output-file"),
                "generated code must use --output-file for lossless transport"
            );
        }
    }

    // Test that generated code uses --query

    #[test]
    fn test_all_shells_use_query_flag() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(
                code.contains("--query"),
                "generated code must use --query for initial filter"
            );
        }
    }

    // --- Behavioral tests: source generated code with a stub snp executable ---

    fn make_stub_snp(dir: &std::path::Path, script: &str) {
        let stub_path = dir.join("snp");
        std::fs::write(&stub_path, script).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&stub_path, std::fs::Permissions::from_mode(0o755)).unwrap();
        }
    }

    fn run_bash(script: &str) -> (bool, String, String) {
        let output = Command::new("bash")
            .args(["-c", script])
            .output()
            .expect("failed to run bash");
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        (output.status.success(), stdout, stderr)
    }

    fn run_bash_interactive(script: &str) -> (bool, String, String) {
        let output = Command::new("bash")
            .args(["--noprofile", "--norc", "-i", "-c", script])
            .output()
            .expect("failed to run interactive bash");
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        (output.status.success(), stdout, stderr)
    }

    fn run_zsh(script: &str) -> (bool, String, String) {
        let output = Command::new("zsh")
            .args(["-f", "-c", script])
            .output()
            .expect("failed to run zsh");
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        (output.status.success(), stdout, stderr)
    }

    fn run_fish(script: &str) -> (bool, String, String) {
        let output = Command::new("fish")
            .args(["-c", script])
            .output()
            .expect("failed to run fish");
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        (output.status.success(), stdout, stderr)
    }

    // Bash behavioral tests

    #[test]
    fn test_bash_new_current_preserves_buffer_and_forwards_arguments() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        let stdin_capture = tmp_dir.path().join("stdin.capture");
        let args_capture = tmp_dir.path().join("args.capture");
        make_stub_snp(
            tmp_dir.path(),
            "#!/bin/bash\ncat > \"$SNP_STDIN_CAPTURE\"\nprintf '%s\\n' \"$@\" > \"$SNP_ARGS_CAPTURE\"\nexit 0\n",
        );

        let code = generate_bash();
        let script = format!(
            "export PATH=\"{}:$PATH\"\nexport SNP_STDIN_CAPTURE=\"{}\"\nexport SNP_ARGS_CAPTURE=\"{}\"\n{}\nREADLINE_LINE=$'printf \"%s\" \"$HOME\"\\necho \"\\$(not run)\" | sed \"s/x/y/\"\\n\\tprintf \"café\"'\nREADLINE_POINT=4\nsnp_new_current --description 'captured command' --tags 'git,release' --library work\nprintf 'RC=%s POINT=%s\\n' \"$?\" \"$READLINE_POINT\"\n",
            tmp_dir.path().to_str().unwrap(),
            stdin_capture.to_str().unwrap(),
            args_capture.to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_bash(&script);
        assert!(ok, "bash failed: {stderr}");
        assert!(
            stdout.contains("RC=0 POINT=4"),
            "unexpected result: {stdout}"
        );
        assert_eq!(
            std::fs::read(&stdin_capture).unwrap(),
            b"printf \"%s\" \"$HOME\"\necho \"\\$(not run)\" | sed \"s/x/y/\"\n\tprintf \"caf\xC3\xA9\""
        );
        let args = std::fs::read_to_string(&args_capture).unwrap();
        assert_eq!(
            args,
            "new\n--command-stdin\n--description\ncaptured command\n--tags\ngit,release\n--library\nwork\n"
        );
    }

    #[test]
    fn test_bash_new_previous_uses_prior_history_event() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        let stdin_capture = tmp_dir.path().join("stdin.capture");
        make_stub_snp(
            tmp_dir.path(),
            "#!/bin/bash\ncat > \"$SNP_STDIN_CAPTURE\"\nexit 0\n",
        );

        let code = generate_bash();
        let script = format!(
            "export PATH=\"{}:$PATH\"\nexport SNP_STDIN_CAPTURE=\"{}\"\n{}\nhistory -c\nhistory -s \"printf '%s' 'previous'\"\nsnp_new_previous --description history\nprintf 'RC=%s\\n' \"$?\"\n",
            tmp_dir.path().to_str().unwrap(),
            stdin_capture.to_str().unwrap(),
            code
        );

        let (ok, _stdout, stderr) = run_bash_interactive(&script);
        assert!(ok, "interactive bash failed: {stderr}");
        assert_eq!(
            std::fs::read(&stdin_capture).unwrap(),
            b"printf '%s' 'previous'\n"
        );
    }

    #[test]
    fn test_zsh_new_current_preserves_buffer_and_cursor() {
        if !shell_exists("zsh") {
            eprintln!("skipping: zsh not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        let stdin_capture = tmp_dir.path().join("stdin.capture");
        make_stub_snp(
            tmp_dir.path(),
            "#!/bin/sh\ncat > \"$SNP_STDIN_CAPTURE\"\nexit 0\n",
        );

        let code = generate_zsh();
        let script = format!(
            "export PATH=\"{}:$PATH\"\nexport SNP_STDIN_CAPTURE=\"{}\"\n{}\nBUFFER=$'printf \"%s\" \"$HOME\"\\nprintf \"zsh: café\"'\nCURSOR=3\nsnp_new_current --description 'zsh capture'\nprintf 'RC=%s CURSOR=%s\\n' \"$?\" \"$CURSOR\"\n",
            tmp_dir.path().to_str().unwrap(),
            stdin_capture.to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_zsh(&script);
        assert!(ok, "zsh failed: {stderr}; stdout: {stdout}");
        assert!(
            stdout.contains("RC=0 CURSOR=3"),
            "unexpected result: {stdout}"
        );
        assert_eq!(
            std::fs::read(&stdin_capture).unwrap(),
            b"printf \"%s\" \"$HOME\"\nprintf \"zsh: caf\xC3\xA9\""
        );
    }

    #[test]
    fn test_bash_success_sets_buffer() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
for ((i=1; i<=$#; i++)); do
    if [[ "${!i}" == "--output-file" ]]; then
        next=$((i+1))
        echo -n "hello world" > "${!next}"
        exit 0
    fi
done
exit 1
"#,
        );

        let code = generate_bash();
        let script = format!(
            r#"export PATH="{}:$PATH"
{}
READLINE_LINE="original buffer"
READLINE_POINT=5
snp_select_raw
echo "BUFFER=$READLINE_LINE"
echo "POINT=$READLINE_POINT""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_bash(&script);
        assert!(ok, "bash failed: {stderr}");
        assert!(
            stdout.contains("BUFFER=hello world"),
            "buffer not updated: {stdout}"
        );
        assert!(stdout.contains("POINT=11"), "point not updated: {stdout}");
    }

    #[test]
    fn test_bash_cancellation_restores_buffer() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
exit 4
"#,
        );

        let code = generate_bash();
        let script = format!(
            r#"export PATH="{}:$PATH"
{}
READLINE_LINE="original buffer"
READLINE_POINT=5
snp_select_raw
echo "BUFFER=$READLINE_LINE"
echo "POINT=$READLINE_POINT""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_bash(&script);
        assert!(ok, "bash failed: {stderr}");
        assert!(
            stdout.contains("BUFFER=original buffer"),
            "buffer not restored: {stdout}"
        );
        assert!(stdout.contains("POINT=5"), "point not restored: {stdout}");
    }

    #[test]
    fn test_bash_operational_failure_restores_buffer() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
echo "error occurred" >&2
exit 1
"#,
        );

        let code = generate_bash();
        let script = format!(
            r#"export PATH="{}:$PATH"
{}
READLINE_LINE="original buffer"
READLINE_POINT=5
snp_select_raw
SNP_RC=$?
echo "RC=$SNP_RC"
echo "BUFFER=$READLINE_LINE"
echo "POINT=$READLINE_POINT""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (_ok, stdout, _stderr) = run_bash(&script);
        assert!(
            stdout.contains("RC=1"),
            "should return error for operational failure: {stdout}"
        );
        assert!(
            stdout.contains("BUFFER=original buffer"),
            "buffer not restored: {stdout}"
        );
        assert!(stdout.contains("POINT=5"), "point not restored: {stdout}");
    }

    #[test]
    fn test_bash_success_with_output_file() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
for ((i=1; i<=$#; i++)); do
    if [[ "${!i}" == "--output-file" ]]; then
        next=$((i+1))
        echo -n "selected command" > "${!next}"
        exit 0
    fi
done
exit 1
"#,
        );

        let code = generate_bash();
        let script = format!(
            r#"export PATH="{}:$PATH"
{}
READLINE_LINE=""
READLINE_POINT=0
snp_select_raw
echo "BUFFER=$READLINE_LINE""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_bash(&script);
        assert!(ok, "bash failed: {stderr}");
        assert!(
            stdout.contains("BUFFER=selected command"),
            "buffer not set: {stdout}"
        );
    }

    #[test]
    fn test_bash_missing_snp_returns_error() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        let code = generate_bash();
        let script = format!(
            r#"export PATH="{}"
{}
READLINE_LINE="original"
READLINE_POINT=0
snp_select_raw
SNP_RC=$?
echo "RC=$SNP_RC"
echo "BUFFER=$READLINE_LINE""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (_ok, stdout, _stderr) = run_bash(&script);
        assert!(
            stdout.contains("RC=1"),
            "should return error for missing snp: {stdout}"
        );
        assert!(
            stdout.contains("BUFFER=original"),
            "buffer should be unchanged: {stdout}"
        );
    }

    #[test]
    fn test_bash_no_output_file_content() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
# Success exit code but no output file written
exit 0
"#,
        );

        let code = generate_bash();
        let script = format!(
            r#"export PATH="{}:$PATH"
{}
READLINE_LINE="original buffer"
READLINE_POINT=5
snp_select_raw
SNP_RC=$?
echo "RC=$SNP_RC"
echo "BUFFER=$READLINE_LINE"
echo "POINT=$READLINE_POINT""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (_ok, stdout, _stderr) = run_bash(&script);
        // mktemp creates the file, so snp returning 0 with empty file means
        // the buffer gets set to empty string (the file content)
        assert!(
            stdout.contains("RC=0"),
            "should return success (file exists, even if empty): {stdout}"
        );
        // Buffer is empty because the empty output file was read
        assert!(
            stdout.contains("BUFFER="),
            "buffer should be empty string from empty output file: {stdout}"
        );
    }

    #[test]
    fn test_bash_multiline_selection() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
for ((i=1; i<=$#; i++)); do
    if [[ "${!i}" == "--output-file" ]]; then
        next=$((i+1))
        printf 'line1\nline2\nline3' > "${!next}"
        exit 0
    fi
done
exit 1
"#,
        );

        let code = generate_bash();
        let script = format!(
            r#"export PATH="{}:$PATH"
{}
READLINE_LINE=""
READLINE_POINT=0
snp_select_raw
echo "BUFFER=$READLINE_LINE""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_bash(&script);
        assert!(ok, "bash failed: {stderr}");
        assert!(
            stdout.contains("BUFFER=line1"),
            "multiline buffer not set: {stdout}"
        );
    }

    // Fish behavioral tests

    #[test]
    fn test_fish_success_sets_buffer() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
for ((i=1; i<=$#; i++)); do
    if [[ "${!i}" == "--output-file" ]]; then
        next=$((i+1))
        echo -n "hello world" > "${!next}"
        exit 0
    fi
done
exit 1
"#,
        );

        let code = generate_fish();
        let script = format!(
            r#"set -gx PATH "{}" $PATH
{}
commandline -r "original buffer"
commandline -C 5
snp_select_raw
echo "BUFFER=(commandline)"
echo "POINT=(commandline -C)""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_fish(&script);
        assert!(ok, "fish failed: {stderr}");
        assert!(
            stdout.contains("BUFFER=hello world"),
            "buffer not updated: {stdout}"
        );
        assert!(stdout.contains("POINT=11"), "point not updated: {stdout}");
    }

    #[test]
    fn test_fish_cancellation_restores_buffer() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
exit 4
"#,
        );

        let code = generate_fish();
        let script = format!(
            r#"set -gx PATH "{}" $PATH
{}
commandline -r "original buffer"
commandline -C 5
snp_select_raw
set -g SNP_RC $status
echo "BUFFER=(commandline)"
echo "POINT=(commandline -C)""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (ok, stdout, stderr) = run_fish(&script);
        assert!(ok, "fish failed: {stderr}");
        assert!(
            stdout.contains("BUFFER=original buffer"),
            "buffer not restored: {stdout}"
        );
        assert!(stdout.contains("POINT=5"), "point not restored: {stdout}");
    }

    #[test]
    fn test_fish_operational_failure_restores_buffer() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        make_stub_snp(
            tmp_dir.path(),
            r#"#!/bin/bash
echo "error occurred" >&2
exit 1
"#,
        );

        let code = generate_fish();
        let script = format!(
            r#"set -gx PATH "{}" $PATH
{}
commandline -r "original buffer"
commandline -C 5
snp_select_raw
set -g SNP_RC $status
echo "RC=$SNP_RC"
echo "BUFFER=(commandline)"
echo "POINT=(commandline -C)""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (_ok, stdout, _stderr) = run_fish(&script);
        assert!(
            stdout.contains("RC=1"),
            "should return error for operational failure: {stdout}"
        );
        assert!(
            stdout.contains("BUFFER=original buffer"),
            "buffer not restored: {stdout}"
        );
        assert!(stdout.contains("POINT=5"), "point not restored: {stdout}");
    }

    #[test]
    fn test_fish_missing_snp_returns_error() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }

        let tmp_dir = tempfile::tempdir().unwrap();
        let code = generate_fish();
        let script = format!(
            r#"set -gx PATH "{}"
{}
commandline -r "original"
commandline -C 0
snp_select_raw
set -g SNP_RC $status
echo "RC=$SNP_RC"
echo "BUFFER=(commandline)""#,
            tmp_dir.path().to_str().unwrap(),
            code
        );

        let (_ok, stdout, _stderr) = run_fish(&script);
        assert!(
            stdout.contains("RC=1"),
            "should return error for missing snp: {stdout}"
        );
        assert!(
            stdout.contains("BUFFER=original"),
            "buffer should be unchanged: {stdout}"
        );
    }
}
