use crate::error::SnipResult;

/// Supported shell types for integration generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellType {
    Bash,
    Zsh,
    Fish,
}

impl std::fmt::Display for ShellType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ShellType::Bash => write!(f, "bash"),
            ShellType::Zsh => write!(f, "zsh"),
            ShellType::Fish => write!(f, "fish"),
        }
    }
}

/// Generate and print shell integration code for the specified shell.
pub fn run(shell: ShellType) -> SnipResult<()> {
    let code = match shell {
        ShellType::Bash => generate_bash(),
        ShellType::Zsh => generate_zsh(),
        ShellType::Fish => generate_fish(),
    };
    print!("{code}");
    Ok(())
}

/// Multiline transport: all shell adapters write the selection to a temp file
/// via `--output-file`, then read it back. This avoids shell-specific quoting
/// issues with `$(...)` stripping trailing newlines and NUL bytes.
fn generate_bash() -> String {
    r#"# Bash integration for snp — Generated by `snp shell init bash`
# Adds snp_select_raw and snp_select_expanded functions.
# No keybindings are installed by default. Bind manually if desired.
# Inspect this output before sourcing.

__snp_select() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi

  local mode="$1"
  local old_line="$READLINE_LINE"
  local old_point="$READLINE_POINT"

  local tmp_file
  tmp_file="$(mktemp "${TMPDIR:-/tmp}/snp-select.XXXXXX")"

  local args=(--output-file "$tmp_file" --"$mode")
  if [[ -n "$READLINE_LINE" ]]; then
    args+=(--query "$READLINE_LINE")
  fi

  snp select "${args[@]}"
  local rc=$?

  if [[ $rc -eq 4 ]] || [[ ! -s "$tmp_file" ]]; then
    rm -f "$tmp_file"
    READLINE_LINE="$old_line"
    READLINE_POINT="$old_point"
    return 0
  fi

  if [[ $rc -ne 0 ]]; then
    rm -f "$tmp_file"
    READLINE_LINE="$old_line"
    READLINE_POINT="$old_point"
    return 1
  fi

  local selected
  IFS= read -r -d '' selected < "$tmp_file"
  rm -f "$tmp_file"

  READLINE_LINE="$selected"
  READLINE_POINT="${#selected}"
}

snp_select_raw() {
  __snp_select raw
}

snp_select_expanded() {
  __snp_select expanded
}

# To bind manually, add to your .bashrc:
#   bind -x '"\C-o": snp_select_raw'
#   bind -x '"\C-o\C-e": snp_select_expanded'
"#
    .to_string()
}

fn generate_zsh() -> String {
    r#"# Zsh integration for snp — Generated by `snp shell init zsh`
# Adds snp_select_raw and snp_select_expanded ZLE widgets.
# No keybindings are installed by default. Bind manually with:
#   bindkey '^O' snp_select_raw
# Inspect this output before sourcing.

__snp_select() {
  if ! command -v snp &>/dev/null; then
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  fi

  local mode="$1"
  local old_buffer="$BUFFER"
  local old_cursor="$CURSOR"

  local tmp_file
  tmp_file="$(mktemp "${TMPDIR:-/tmp}/snp-select.XXXXXX")"

  local -a args=(--output-file "$tmp_file" --"$mode")
  if [[ -n "$BUFFER" ]]; then
    args+=(--query "$BUFFER")
  fi

  snp select "${args[@]}"
  local rc=$?

  if [[ $rc -eq 4 ]] || [[ ! -s "$tmp_file" ]]; then
    rm -f "$tmp_file"
    BUFFER="$old_buffer"
    CURSOR="$old_cursor"
    zle redisplay
    return
  fi

  if [[ $rc -ne 0 ]]; then
    rm -f "$tmp_file"
    BUFFER="$old_buffer"
    CURSOR="$old_cursor"
    zle redisplay
    return
  fi

  local selected
  IFS= read -r -d '' selected < "$tmp_file"
  rm -f "$tmp_file"

  BUFFER="$selected"
  CURSOR="${#BUFFER}"
  zle redisplay
}

zle -N snp_select_raw () { __snp_select raw }
zle -N snp_select_expanded () { __snp_select expanded }

# To bind, add to your .zshrc:
#   bindkey '^O' snp_select_raw
#   bindkey '^O^E' snp_select_expanded
"#
    .to_string()
}

fn generate_fish() -> String {
    r#"# Fish integration for snp — Generated by `snp shell init fish`
# Adds snp_select_raw and snp_select_expanded functions.
# No keybindings are installed by default. Bind manually with:
#   bind \co snp_select_raw
# Inspect this output before sourcing.

function __snp_select --argument-names mode
  if not command -q snp
    echo "snp: 'snp' not found in PATH" >&2
    return 1
  end

  set -l old_cmdline (commandline)
  set -l old_cursor (commandline -C)

  set -l tmp_file (mktemp "/tmp/snp-select.XXXXXX")

  set -l snp_args --output-file "$tmp_file" --"$mode"
  if test -n "$old_cmdline"
    set snp_args $snp_args --query "$old_cmdline"
  end

  snp select $snp_args
  set -l rc $status

  if test $rc -eq 4 -o ! -s "$tmp_file"
    rm -f "$tmp_file"
    commandline -C "$old_cursor"
    commandline -r "$old_cmdline"
    return
  end

  if test $rc -ne 0
    rm -f "$tmp_file"
    commandline -C "$old_cursor"
    commandline -r "$old_cmdline"
    return 1
  end

  set -l selected (cat "$tmp_file" | string split0)
  rm -f "$tmp_file"

  commandline -r "$selected"
  commandline -C (string length -- "$selected")
end

function snp_select_raw
  __snp_select raw
end

function snp_select_expanded
  __snp_select expanded
end

# To bind, add to your config.fish:
#   bind \co snp_select_raw
#   bind \co\e snp_select_expanded
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    #[test]
    fn test_shell_type_display() {
        assert_eq!(ShellType::Bash.to_string(), "bash");
        assert_eq!(ShellType::Zsh.to_string(), "zsh");
        assert_eq!(ShellType::Fish.to_string(), "fish");
    }

    #[test]
    fn test_bash_generation_contains_required_elements() {
        let code = generate_bash();
        assert!(code.contains("snp_select_raw"));
        assert!(code.contains("snp_select_expanded"));
        assert!(code.contains("__snp_select"));
        assert!(code.contains("READLINE_LINE"));
        assert!(code.contains("READLINE_POINT"));
        assert!(code.contains("--output-file"));
        assert!(code.contains("--query"));
        assert!(code.contains("snp select"));
        assert!(code.contains("mktemp"));
        assert!(code.contains("command -v snp"));
    }

    #[test]
    fn test_zsh_generation_contains_required_elements() {
        let code = generate_zsh();
        assert!(code.contains("snp_select_raw"));
        assert!(code.contains("snp_select_expanded"));
        assert!(code.contains("__snp_select"));
        assert!(code.contains("BUFFER"));
        assert!(code.contains("CURSOR"));
        assert!(code.contains("zle -N"));
        assert!(code.contains("zle redisplay"));
        assert!(code.contains("--output-file"));
        assert!(code.contains("--query"));
        assert!(code.contains("snp select"));
    }

    #[test]
    fn test_fish_generation_contains_required_elements() {
        let code = generate_fish();
        assert!(code.contains("snp_select_raw"));
        assert!(code.contains("snp_select_expanded"));
        assert!(code.contains("__snp_select"));
        assert!(code.contains("commandline"));
        assert!(code.contains("commandline -C"));
        assert!(code.contains("--output-file"));
        assert!(code.contains("--query"));
        assert!(code.contains("snp select"));
    }

    #[test]
    fn test_no_eval_in_generated_code() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(!code.contains("eval "));
            assert!(!code.contains("eval\""));
            assert!(!code.contains("eval '"));
        }
    }

    #[test]
    fn test_cancellation_preserves_buffer() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(code.contains("4"));
            assert!(code.contains("old_"));
        }
    }

    #[test]
    fn test_all_shells_check_for_snp() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(code.contains("snp"));
            assert!(code.contains("not found") || code.contains("not found"));
        }
    }

    // H1: Generated syntax tests — validate with shell parsers

    fn shell_exists(name: &str) -> bool {
        Command::new("which")
            .arg(name)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    #[test]
    fn test_bash_syntax_check() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }
        let code = generate_bash();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let output = Command::new("bash")
            .args(["-n", tmp.path().to_str().unwrap()])
            .output()
            .expect("failed to run bash -n");

        assert!(
            output.status.success(),
            "bash -n failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_zsh_syntax_check() {
        if !shell_exists("zsh") {
            eprintln!("skipping: zsh not found");
            return;
        }
        let code = generate_zsh();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let output = Command::new("zsh")
            .args(["-n", tmp.path().to_str().unwrap()])
            .output()
            .expect("failed to run zsh -n");

        assert!(
            output.status.success(),
            "zsh -n failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_fish_syntax_check() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }
        let code = generate_fish();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let output = Command::new("fish")
            .args(["--no-execute", tmp.path().to_str().unwrap()])
            .output()
            .expect("failed to run fish --no-execute");

        assert!(
            output.status.success(),
            "fish --no-execute failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    // H2: Function-definition tests — source and verify functions exist

    #[test]
    fn test_bash_functions_exist_after_source() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }
        let code = generate_bash();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let check = format!(
            ". {} && type snp_select_raw && type snp_select_expanded",
            tmp.path().to_str().unwrap()
        );
        let output = Command::new("bash")
            .args(["-c", &check])
            .output()
            .expect("failed to run bash");

        assert!(
            output.status.success(),
            "bash function check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_zsh_functions_exist_after_source() {
        if !shell_exists("zsh") {
            eprintln!("skipping: zsh not found");
            return;
        }
        let code = generate_zsh();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let check = format!(
            "source {} && which snp_select_raw && which snp_select_expanded",
            tmp.path().to_str().unwrap()
        );
        let output = Command::new("zsh")
            .args(["-c", &check])
            .output()
            .expect("failed to run zsh");

        assert!(
            output.status.success(),
            "zsh function check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn test_fish_functions_exist_after_source() {
        if !shell_exists("fish") {
            eprintln!("skipping: fish not found");
            return;
        }
        let code = generate_fish();
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &code).unwrap();

        let check = format!(
            "source {} && functions -q snp_select_raw && functions -q snp_select_expanded",
            tmp.path().to_str().unwrap()
        );
        let output = Command::new("fish")
            .args(["-c", &check])
            .output()
            .expect("failed to run fish");

        assert!(
            output.status.success(),
            "fish function check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    // H5: Non-execution sentinel — verify widget doesn't execute

    #[test]
    fn test_bash_does_not_execute_on_source() {
        if !shell_exists("bash") {
            eprintln!("skipping: bash not found");
            return;
        }
        let sentinel = tempfile::NamedTempFile::new().unwrap();
        let sentinel_path = sentinel.path().to_str().unwrap().to_string();
        drop(sentinel);

        let code = generate_bash();
        let script = format!(
            "{}\nsnp_select_raw() {{ echo '{}' > '{}'; }}",
            code, "SENTINEL_CREATED", sentinel_path
        );

        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &script).unwrap();

        // Source the file — functions are defined but not invoked
        let output = Command::new("bash")
            .args(["-c", &format!(". {}", tmp.path().to_str().unwrap())])
            .output()
            .expect("failed to run bash");

        assert!(
            output.status.success(),
            "bash source failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        // Verify sentinel was NOT created
        assert!(
            !std::path::Path::new(&sentinel_path).exists(),
            "sentinel file was created during source — non-execution violated"
        );
    }

    // H4: Special-character tests in function content

    #[test]
    fn test_bash_handles_quotes_in_generated_code() {
        let code = generate_bash();
        assert!(code.contains("\"snp\"") || code.contains("'snp'"));
    }

    #[test]
    fn test_zsh_handles_quotes_in_generated_code() {
        let code = generate_zsh();
        assert!(code.contains("\"snp\"") || code.contains("'snp'"));
    }

    #[test]
    fn test_fish_handles_quotes_in_generated_code() {
        let code = generate_fish();
        assert!(code.contains("\"snp\"") || code.contains("'snp'"));
    }

    // Test that output_file flag is handled for cancellation cleanup

    #[test]
    fn test_output_file_cleanup_on_cancellation() {
        let tmp = tempfile::NamedTempFile::new().unwrap();
        let path = tmp.path().to_path_buf();
        drop(tmp);

        std::fs::write(&path, "test").unwrap();
        assert!(path.exists());

        let _ = std::fs::remove_file(&path);
        assert!(!path.exists());
    }

    // Test that generated code uses --output-file, not stdout

    #[test]
    fn test_all_shells_use_output_file() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(
                code.contains("--output-file"),
                "generated code must use --output-file for lossless transport"
            );
        }
    }

    // Test that generated code uses --query

    #[test]
    fn test_all_shells_use_query_flag() {
        for code in [generate_bash(), generate_zsh(), generate_fish()] {
            assert!(
                code.contains("--query"),
                "generated code must use --query for initial filter"
            );
        }
    }
}
