#!/usr/bin/env python3
"""
Build script for bundled Halloy-compatible themes.

Reads every `themes/*.toml` in the project root, LZMA-compresses each
(using stdlib's `lzma` module with the XZ container format that matches
the `lzma-rs` Rust crate's decoder), base64-encodes the bytes, and emits
a single Rust source file at `src/ui/_generated_bundled_themes.rs`.

The `Cyber Red` theme is treated specially: it's `include_str!`'d directly
so the binary always has a usable theme on the very first launch, before
the `themes/` directory has been seeded from the compressed bundle.

Usage:
    python3 scripts/build_themes.py

This is also invoked automatically by `build.rs` whenever any file in
`themes/` is newer than the generated output.
"""
from __future__ import annotations

import base64
import io
import lzma
import re
import sys
from pathlib import Path

# Paths are relative to the project root (where Cargo.toml lives).
ROOT = Path(__file__).resolve().parent.parent
THEMES_DIR = ROOT / "themes"
OUTPUT = ROOT / "src" / "ui" / "_generated_bundled_themes.rs"

# Filename of the hardcoded, uncompressed fallback theme. It must exist
# in themes/ before running this script. The basename (no .toml) is
# referenced by the picker as a "default" name.
DEFAULT_THEME_FILENAME = "Cyber Red.toml"

# Filename validation: permissive enough to allow Halloy's community
# naming (e.g. "Catppuccin Mocha.toml", "Discord (80_ Saturation).toml")
# but strict enough to reject path-traversal attempts.
FILENAME_RE = re.compile(r"^[\w ()\-.,]+\.toml$", re.UNICODE)


def validate_filename(name: str) -> str:
    if not FILENAME_RE.match(name):
        raise ValueError(
            f"Refusing to bundle theme {name!r}: filename must match "
            f"{FILENAME_RE.pattern!r}"
        )
    return name


def compress_xz(data: bytes) -> bytes:
    """LZMA-compress with the XZ container format (matches lzma-rs xz_decompress).

    The default XZ preset (level 6) is a good speed/ratio balance. The
    resulting bytes are typically ~30% of the original size for small
    text files.
    """
    return lzma.compress(data, format=lzma.FORMAT_XZ, preset=6)


def collect_themes() -> list[Path]:
    """Return all .toml files in themes/, sorted by name for determinism."""
    if not THEMES_DIR.is_dir():
        raise FileNotFoundError(f"themes/ directory not found at {THEMES_DIR}")
    return sorted(p for p in THEMES_DIR.iterdir() if p.suffix == ".toml")


def generate_rust(themes: list[Path]) -> str:
    """Produce the full text of the generated Rust file."""
    if not themes:
        raise RuntimeError("No themes found in themes/")

    # Separate the default theme from the rest.
    default_path = None
    bundled: list[tuple[str, str]] = []  # (basename_no_ext, base64_payload)
    for path in themes:
        validate_filename(path.name)
        basename = path.stem  # e.g. "Cyber Red"
        if path.name == DEFAULT_THEME_FILENAME:
            default_path = path
            continue
        raw = path.read_bytes()
        compressed = compress_xz(raw)
        encoded = base64.b64encode(compressed).decode("ascii")
        bundled.append((basename, encoded))

    if default_path is None:
        raise RuntimeError(
            f"Default theme {DEFAULT_THEME_FILENAME!r} not found in themes/. "
            f"This file is required as the uncompressed runtime fallback."
        )

    # Sort bundled themes alphabetically (case-insensitive) for deterministic
    # output across machines. The TUI's runtime list is sorted separately.
    bundled.sort(key=lambda kv: kv[0].casefold())

    lines: list[str] = []
    lines.append(
        "// @generated by scripts/build_themes.py — do not edit by hand."
    )
    lines.append(
        f"// Source: {len(bundled) + 1} themes in {THEMES_DIR.relative_to(ROOT)}/"
    )
    lines.append(
        "// Regenerate by running: python3 scripts/build_themes.py"
    )
    lines.append("//")
    lines.append("// LZMA compression (XZ container) via Python's stdlib `lzma`.")
    lines.append(
        "// Decoded at runtime by the `lzma-rs` crate (xz_decompress)."
    )
    lines.append("//")
    lines.append(
        "// The default theme is embedded as a Rust raw string literal so the"
    )
    lines.append(
        "// published crate does not need the source `themes/` directory at"
    )
    lines.append(
        "// build time. All other themes are LZMA-compressed in the table"
    )
    lines.append(
        "// below and decoded on first launch."
    )
    lines.append("")
    # Silence the dead_code lint for items that may not all be referenced
    # during a particular build (e.g. tests vs. release).
    lines.append("#![allow(dead_code, unused_imports)]")
    lines.append("")
    lines.append("use crate::error::SnipResult;")
    lines.append("use base64::Engine as _;")
    lines.append("")
    lines.append(
        '/// Uncompressed hardcoded fallback theme. Embedded as a Rust raw'
    )
    lines.append(
        "/// string literal so the binary always has a usable theme on the"
    )
    lines.append(
        "/// very first launch, before the user's `themes/` directory has"
    )
    lines.append(
        "/// been seeded from the compressed bundle. The original file is"
    )
    lines.append(f"/// `themes/{DEFAULT_THEME_FILENAME}` — editing that file and")
    lines.append(
        "/// re-running this script will update the embedded copy."
    )

    # Embed the default theme as a Rust raw string literal. Pick a
    # delimiter (`#` count) that cannot appear inside the file content.
    raw_default = default_path.read_text(encoding="utf-8")
    delim_count = 1
    needle_open = '"' + ("#" * delim_count)
    needle_close = ("#" * delim_count) + '"'
    while needle_open in raw_default or needle_close in raw_default:
        delim_count += 1
        needle_open = '"' + ("#" * delim_count)
        needle_close = ("#" * delim_count) + '"'
    delim = "#" * delim_count
    lines.append(
        f'pub const DEFAULT_BUNDLED: &str = r{delim}"{raw_default}"{delim};'
    )
    lines.append("")
    lines.append("/// One bundled theme: a name and a base64-encoded LZMA-compressed TOML body.")
    lines.append("#[derive(Debug, Clone, Copy)]")
    lines.append("pub struct BundledTheme {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub payload_b64: &'static str,")
    lines.append("}")
    lines.append("")
    lines.append(
        f"/// All bundled themes (excluding the default). Sorted by name."
    )
    lines.append(
        f"pub const BUNDLED: &[BundledTheme] = &["
    )
    for name, encoded in bundled:
        # Escape any backslashes/quotes in the name (defensive — filenames
        # matching FILENAME_RE shouldn't contain these, but the script
        # runs in a context where mistakes are easy).
        safe_name = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    BundledTheme {{ name: "{safe_name}", payload_b64: "{encoded}" }},')
    lines.append("];")
    lines.append("")
    lines.append(
        "/// Decompress every bundled theme into `(name, toml_text)` pairs."
    )
    lines.append(
        "/// Intended for the one-time `ThemeManager::init_themes_dir`"
    )
    lines.append(
        "/// extraction. Do not call in hot paths — each call decodes"
    )
    lines.append(
        "/// ~50 KiB of LZMA data."
    )
    lines.append(
        "pub fn bundled_themes_decoded() -> SnipResult<std::vec::Vec<(String, String)>> {"
    )
    lines.append("    BUNDLED")
    lines.append("        .iter()")
    lines.append("        .map(|b| {")
    lines.append("            let compressed = base64::engine::general_purpose::STANDARD")
    lines.append("                .decode(b.payload_b64)")
    lines.append("                .map_err(|_| {")
    lines.append(
        '                    crate::SnipError::runtime_error("bundled theme: invalid base64", None)'
    )
    lines.append("                })?;")
    lines.append("            let mut toml_bytes = std::vec::Vec::new();")
    lines.append("            lzma_rs::xz_decompress(")
    lines.append("                &mut compressed.as_slice(),")
    lines.append("                &mut toml_bytes,")
    lines.append("            )")
    lines.append("            .map_err(|_| {")
    lines.append(
        '                crate::SnipError::runtime_error("bundled theme: invalid xz stream", None)'
    )
    lines.append("            })?;")
    lines.append(
        "            let toml_text = String::from_utf8(toml_bytes).map_err(|_| {"
    )
    lines.append(
        '                crate::SnipError::runtime_error("bundled theme: non-utf-8 toml", None)'
    )
    lines.append("            })?;")
    lines.append(
        "            Ok::<(String, String), crate::SnipError>((b.name.to_string(), toml_text))"
    )
    lines.append("        })")
    lines.append(
        "        .collect::<Result<Vec<(String, String)>, crate::SnipError>>()"
    )
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    themes = collect_themes()
    if not themes:
        print(f"error: no .toml files in {THEMES_DIR}", file=sys.stderr)
        return 1
    try:
        output = generate_rust(themes)
    except (ValueError, RuntimeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    # Print a brief summary.
    total_compressed = sum(
        len(base64.b64decode(b[1])) for b in [
            (n, e) for (n, e) in [
                # Re-parse the output to count? Simpler: re-walk the dirs.
            ]
        ]
    )
    print(
        f"wrote {OUTPUT.relative_to(ROOT)} "
        f"({len(themes)} themes, "
        f"{OUTPUT.stat().st_size:,} bytes)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
